#ifndef THEMEDATABASE_H
#define THEMEDATABASE_H

char *DBlistpng[MAXTHEMES] = {
	"animalcrossing.png",
	"batmanv1.png",
	"blackmage.png",
	"blackpirate.png",
	"bleach.png",
	"bowser.png",
	"broly.png",
	"car.png",
	"cars.png",
	"codegeass.png",
	"constantine.png",
	"darkwiioriginal.png",
	"darkwiiblue.png",
	"darkwiigreen.png",
	"darkwiiorange.png",
	"darkwiipink.png",
	"darkwiipurple.png",
	"darkwiired.png",
	"darkwiiwhite.png",
	"darkwiiyellow.png",
	"evildead.png",
	"ghostbusters.png",
	"jurassicpark3.png",
	"kingdomhearts.png",
	"leopardOS.png",
	"limewii.png",
	"luigi.png",
	"madworld.png",
	"majorasmask.png",
	"mario.png",
	"mariokart.png",
	"matrix.png",
	"matrixreloaded.png",
	"metroid.png",
	"mortalkombat.png",
	"muse.png",
	"nightmareb4xmas.png",
	"oldschoolnintendo.png",
	"psychedelic.png",
	"ratchetandclank.png",
	"rockband2.png",
	"shadowthehedgehog.png",
	"Spiderman.png",
	"superherosquad.png",
	"supersonic.png",
	"thesimpsons.png",
	"thundercats.png",
	"tmnt.png",
	"tombraider.png",
	"trueblood.png",
	"winxpos.png",
	"wolverine.png",
	"zelda.png"
};


char *DBThemelist[MAXTHEMES] =
{
	"Animal Crossing",
	"Batman v1",
	"Black Mage",
	"Black Pirate",
	"Bleach",
	"Bowser",
	"Broly",
	"Car",
	"Cars",
	"Code Geass",
	"Constantine",
	"Dark Wii Original",
	"Dark Wii Blue",
	"Dark Wii Green",
	"Dark Wii Orange",
	"Dark Wii Pink",
	"Dark Wii Purple",
	"Dark Wii Red",
	"Dark Wii White",
	"Dark Wii Yellow",
	"Evil Dead",
	"Ghost Busters",
	"Jurassic Park 3",
	"Kingdom Hearts",
	"Leopard OS",
	"Lime Wii",
	"Luigi",
	"Mad World",
	"Majoras Mask",
	"Mario",
	"Mario Kart",
	"Matrix",
	"Matrix Reloaded",
	"Metroid",
	"Mortal Kombat",
	"Muse",
	"Nightmare B4 Xmas",
	"Old School Nintendo",
	"Psychedelic",
	"Ratchet and Clank",
	"Rockband 2",
	"Shadow The Hedgehog",
	"Spiderman",
	"Super Hero Squad",
	"Super Sonic",
	"The Simpsons",
	"Thunder Cats",
	"TMNT",
	"Tomb Raider",
	"True Blood",
	"Win XP OS",
	"Wolverine",
	"Zelda"
};
char *DBThemelist_nospaces[MAXTHEMES] =
{
	"AnimalCrossing",
	"Batmanv1",
	"BlackMage",
	"BlackPirate",
	"Bleach",
	"Bowser",
	"Broly",
	"Car",
	"Cars",
	"CodeGeass",
	"Constantine",
	"DarkWiiOriginal",
	"DarkWiiBlue",
	"DarkWiiGreen",
	"DarkWiiOrange",
	"DarkWiiPink",
	"DarkWiiPurple",
	"DarkWiiRed",
	"DarkWiiWhite",
	"DarkWiiYellow",
	"EvilDead",
	"GhostBusters",
	"JurassicPark3",
	"KingdomHearts",
	"LeopardOS",
	"LimeWii",
	"Luigi",
	"MadWorld",
	"MajorasMask",
	"Mario",
	"MarioKart",
	"Matrix",
	"MatrixReloaded",
	"Metroid",
	"MortalKombat",
	"Muse",
	"NightmareB4Xmas",
	"OldSchoolNintendo",
	"Psychedelic",
	"RatchetandClank",
	"Rockband2",
	"ShadowTheHedgehog",
	"Spiderman",
	"SuperHeroSquad",
	"SuperSonic",
	"TheSimpsons",
	"ThunderCats",
	"TMNT",
	"TombRaider",
	"TrueBlood",
	"WinXPOS",
	"Wolverine",
	"Zelda"
};

char *DBThemelistDL[MAXTHEMES] =
{
	"animal_crossing.mym",
	"batman_v1.mym",
	"black_mage.mym",
	"black_pirate.mym",
	"bleach.mym",
	"bowser.mym",
	"broly.mym",
	"car.mym",
	"cars.mym",
	"code_geass.mym", 
	"constantine.mym", // 10
	"dark_wii_original.mym",
	"dark_wii_blue",
	"dark_wii_green",
	"dark_wii_orange",
	"dark_wii_pink",
	"dark_wii_purple",
	"dark_wii_red",
	"dark_wii_white",
	"dark_wii_yellow",
	"evil_dead.mym",
	"ghost_busters.mym",
	"jurassic_park_3.mym",
	"kingdom_hearts.mym",
	"leopard_os.mym",
	"lime_wii.mym",
	"luigi.mym",
	"mad_world.mym",
	"majoras_mask.mym",
	"mario.mym",
	"mario_kart.mym",
	"matrix.mym",
	"matrix_reloaded.mym",
	"metroid.mym",
	"mortal_kombat.mym",
	"muse.mym",
	"nightmare_b4_xmas.mym",
	"old_school_nintendo.mym",
	"psychedelic.mym",
	"ratchet_and_clank.mym",
	"rockband_2.mym",
	"shadow_the_hedgehog.mym",
	"Spiderman.mym",
	"super_hero_squad.mym",
	"super_sonic.mym",
	"the_simpsons.mym",
	"thunder_cats.mym",
	"tmnt.mym",
	"tomb_raider.mym",
	"true_blood.mym",
	"win_xp_os.mym",
	"wolverine.mym",
	"zelda.mym"
};























#endif // THEMEDATABASE_H