#ifndef THEMEDATABASE_H
#define THEMEDATABASE_H

char *Theme_Png[MAXTHEMES] = {
"adventuretime.png",
"realmonsters.png",
"american_dad.png",
"american_dadv2.png",
"amongusv1.png",
"amongusv2.png",
"angrybeavers.png",
"animalcrossing.png",
"animalcrossingv2.png",
"apple.png",
"aquateenhungerforce.png",
"army_of_darkness.png",
"arsenal.png",
"falcons.png",
"avengers.png",
"backtothefuture.png",
"bakugan.png",
"barcelona.png",
"battlefordreamisland.png",
"batmanv1.png",
"batmanv2.png",
"biggie.png",
"billymays.png",
"blackgold.png",
"blackmage.png",
"blackpirate.png",
"blackpirate.png",
"blacksabbath.png",
"bleach.png",
"bluesclues.png",
"bluewii_beta.png",
"bobobo.png",
"boondocksaints.png",
"boston_redsocks.png",
"bowser.png",
"bratz.png",
"broly.png",
"buffalo_bills.png",
"buffy.png",
"busytown.png",
"callofduty.png",
"caveman.png",
"car.png",
"carolina_panthers.png",
"cars.png",
"castlevania.png",
"catdog.png",
"celtic.png",
"chainsaw_man.png",
"check_mii_out.png",
"chicago_bears.png",
"chicago_blackhawks.png",
"chicago_bulls.png",
"chowder.png",
"xmas.png",
"chronotrigger.png",
"clockworkorange.png",
"clubpenguin.png",
"knd.png",
"codegeass.png",
"conduit.png",
"conduitv2.png",
"constantine.png",
"courage.png",
"creature_cases.png",
"daisy.png",
"dallas_cowboys.png",
"dandadan.png",
"dark_umbra_v1.png",
"dark_umbra_v2.png",
"darkwii_extended.png",
"darkwii_plus.png",
"darkwiioriginal.png",
"darkwiiblue.png",
"darkwiigreen.png",
"darkwiiorange.png",
"darkwiipink.png",
"darkwiipurple.png",
"darkwiired.png",
"darkwiiwhite.png",
"darkwiiyellow.png",
"dark_scooby.png",
"deathnote.png",
"demonslayer.png",
"dethklok.png",
"detroit_lions.png",
"dexters_lab.png",
"diablo_3.png",
"discord.png",
"dogman.png",
"dolphins.png",
"dragonballzv1.png",
"dragonballzv2.png",
"drawntogether.png",
"drwho.png",
"dukes.png",
"dx.png",
"eagles.png",
"earthbound.png",
"earthboundv2.png",
"earthboundv3.png",
"ededdeddy.png",
"emoblue.png",
"emogreen.png",
"emopink.png",
"emopurple.png",
"emored.png",
"evildead.png",
"excitebots.png",
"eyes.png",
"fairlyoddparents.png",
"familyguy.png",
"fantasticfour.png",
"fantasy.png",
"fatalbert.png",
"felix.png",
"fightclub.png",
"finalfantasy7.png",
"firewii.png",
"flintstones.png",
"flowerpower.png",
"fosters_home.png",
"fridaynightfunkin.png",
"fridaythe13th.png",
"fullmetalalchemist.png",
"futurama.png",
"gaara.png",
"gambit.png",
"garfield.png",
"gearsofwar.png",
"ghostbusters.png",
"gijoe.png",
"goldensun.png",
"gorillaz.png",
"gothic.png",
"gratefuldead.png",
"greenbay_packers.png",
"grim.png",
"gumball.png",
"gundam.png",
"handdrawn.png",
"treefriends.png",
"hellokitty.png",
"hellskitchen.png",
"heman.png",
"heros.png",
"arnold.png",
"homestar.png",
"hot_wheels.png",
"hundreds.png",
"icarly.png",
"illusionsofgaia.png",
"imports.png",
"inbetweeners.png",
"indianajones.png",
"colts.png",
"icp.png",
"itsamemario.png",
"jaybob.png",
"jetsons.png",
"jetsetradio.png",
"jimmyneutron.png",
"jimmyneutronv2.png",
"joker.png",
"jurassicpark3.png",
"jurassicworld.png",
"kidicarus.png",
"kingdomhearts.png",
"kingofthehill.png",
"kirby.png",
"kirbyadventures.png",
"kiss.png",
"korn.png",
"lego.png",
"legobatman.png",
"leopardos.png",
"limewii.png",
"limpbizkit.png",
"looneytoons.png",
"larams.png",
"lost.png",
"luigi.png",
"luigiv2.png",
"luna_chip_inkie.png",
"lupin.png",
"m&ms.png",
"madworld.png",
"mad_world_v2.png",
"majorasmask.png",
"united.png",
"manhunt.png",
"maria.png",
"mario.png",
"mariokart.png",
"marioparty8.png",
"martin_abel.png",
"matrix.png",
"matrixreloaded.png",
"megaman.png",
"melonofharuhi.png",
"metalgearsolid.png",
"metallica.png",
"metroid.png",
"metroid_prime.png",
"metroid_samusvisor.png",
"mets.png",
"minecraft.png",
"minions.png",
"minionsv2.png",
"mistforest.png",
"modmii.png",
"monkeys.png",
"monopoly.png",
"monsters_inc.png",
"canadians.png",
"mortalkombat.png",
"mrdriller.png",
"muse.png",
"myhero.png",
"poni.png",
"naruto.png",
"saints.png",
"patriots.png",
"rangers.png",
"yankees.png",
"nightmareb4xmas.png",
"freddy.png",
"nightsintodreams.png",
"nirvana.png",
"nomoreheros.png",
"raiders.png",
"oasis.png",
"okami.png",
"oldschoolnintendo.png",
"outlawstar.png",
"outerspace.png",
"spacev2.png",
"ozzy.png",
"pacman.png",
"pawpatrol.png",
"pearl_jam.png",
"penguinsofmad.png",
"phoenixwright.png",
"pikmin.png",
"pinkfloyd.png",
"pinkwii.png",
"pinkybrain.png",
"pirateskulls.png",
"penguins.png",
"steelers.png",
"pizzatower.png",
"popeye.png",
"pokemon.png",
"predator.png",
"princess_ariel_v1.png",
"princess_ariel_v2.png",
"princess_ariel_v3.png",
"Psychedelic.png",
"punch_out.png",
"punisher.png",
"randyorton.png",
"ratchetandclank.png",
"rc24_blue.png",
"rc24_red.png",
"redwiimotion.png",
"regularshow.png",
"renstimpy.png",
"re4.png",
"rey_mysterio.png",
"rhythmheaven.png",
"ricknmorty.png",
"ricknmortyv2.png",
"roblox.png",
"robotchicken.png",
"rockband2.png",
"rockosmodernlife.png",
"rollingstones.png",
"rondo_of_blood.png",
"rugrats.png",
"saw.png",
"scarface.png",
"scoobydoo.png",
"secretsofmana.png",
"seinfeld.png",
"sendo.png",
"sesamestreet.png",
"shadowthehedgehog.png",
"shana.png",
"shinedown.png",
"silverthehedgehog.png",
"smashbros.png",
"smokers.png",
"snoopy.png",
"sonic3.png",
"sonicfrontiers.png",
"sonicriders.png",
"sonsofanarchy.png",
"southpark.png",
"southparkv2.png",
"spawn.png",
"spiceandwolf.png",
"spiderman.png",
"spongebob.png",
"spongebobv2.png",
"squidbillies.png",
"starcraft.png",
"starfoxzero.png",
"stargate.png",
"startrek.png",
"starwars.png",
"starwarsunleashed.png",
"steelwii.png",
"storms.png",
"streetfighter.png",
"superherosquad.png",
"supermariobros3.png",
"supermariorpg.png",
"supermariosunshine.png",
"superpapermario.png",
"supersonic.png",
"simpsons_v1.png",
"simpsons_v2.png",
"simpsons_v3.png",
"tails.png",
"tamagotchi.png",
"tamagotchiv2.png",
"terminator.png",
"terranigma.png",
"thundercats.png",
"tmnt.png",
"tenaciousD.png",
"tomandjerry.png",
"tomandjerryv2.png",
"tombraider.png",
"leafs.png",
"totaldrama.png",
"toxictoons.png",
"toystory.png",
"toystoryv2.png",
"transformers.png",
"trialsofmana.png",
"trigun.png",
"tropicalteal.png",
"trueblood.png",
"ultimatedarkwii.png",
"usbanimals.png",
"canucks.png",
"vegeta.png",
"vista.png",
"wackyraces.png",
"wallacegromit.png",
"walleye.png",
"warioware.png",
"capitals.png",
"weaponx.png",
"whereswally.png",
"whitestripes.png",
"whitewii.png",
"wiid.png",
"wiiadict.png",
"wiifit.png",
"wiiparty.png",
"wiipartyv2.png",
"wiisports.png",
"wiistartfires.png",
"wiiu.png",
"windows7.png",
"winxpos.png",
"woodwii.png",
"woodywoodpecker.png",
"wolverine.png",
"wolverinev2.png",
"wweraw.png",
"xbox360.png",
"xmen.png",
"yoshi.png",
"yugioh.png",
"zelda.png",
"zelda2.png",
"minishcap.png",
"zelda_v4.png",
"zombwii.png"
};


char *Theme_List[MAXTHEMES] = {
"Adventure Time",
"Ahh Real Monsters",
"American Dad",
"American Dad v2",
"Among Us v1",
"Among Us v2",
"Angry Beavers",
"Animal Crossing",
"Animal Crossing v2",
"Apple",
"Aqua Teen Hunger Force",
"Army of Darkness",
"Arsenal FC",
"Atlanta Falcons",
"Avengers",
"Back to the Future",
"Bakugan",
"FC Barcelona",
"Battle for Dream Island",
"Batman v1",
"Batman v2",
"Notorious B.I.G.",
"Billy Mays",
"Black Gold",
"Black Mage",
"Black Pirate",
"Black Pirate v2",
"Black Sabbath",
"Bleach",
"Blue's Clue's",
"Blue Wii Beta",
"BoBoBo",
"Boondock Saints",
"Boston Red Socks",
"Bowser",
"Bratz",
"Broly",
"Buffalo Bills",
"Buffy the Vampyr Killer",
"Busy Town",
"Call of Duty",
"Captain Caveman",
"Car",
"Carolina Panthers",
"Cars",
"Castlevania",
"CatDog",
"Celtic FC",
"Chainsaw Man",
"Check Mii Out",
"Chicago Bears",
"Chicago Black Hawks",
"Chicago Bulls",
"Chowder",
"Christmas",
"Chrono Trigger",
"Clock Work Orange",
"Club Penguin",
"CodeName: Kids Next Door",
"Code Geass",
"Conduit",
"Conduit v2",
"Constantine",
"Courage",
"Creature Cases",
"Daisy Blaize",
"Dallas Cowboys",
"Dan Da Dan",
"Dark Umbra v1",
"Dark Umbra v2",
"Dark Wii Extended",
"Dark Wii Plus",
"Dark Wii Original",
"Dark Wii Blue",
"Dark Wii Green",
"Dark Wii Orange",
"Dark Wii Pink",
"Dark Wii Purple",
"Dark Wii Red",
"Dark Wii White",
"Dark Wii Yellow",
"Dark Wii SE",
"Death Note",
"Demon Slayer",
"Deth Klok",
"Detroit Lions",
"Dexter's Laboratory",
"Diablo 3",
"Discord",
"Dog Man",
"Dolphins",
"Dragon Ball Z v1",
"Dragon Ball Z v2",
"Drawn Together",
"Dr Who",
"Dukes of Hazzard",
"De-Generation X",
"Eagles",
"Earth Bound",
"Earth Bound v2",
"Earth Bound v3",
"Ed, Edd, n' Eddy",
"Emo Blue",
"Emo Green",
"Emo Pink",
"Emo Purple",
"Emo Red",
"Evil Dead",
"Excite Bots",
"Eyes",
"Fairly Odd Parents",
"Family Guy",
"Fantastic Four",
"Fantasy",
"Fat Albert",
"Felix the Cat",
"Fight Club",
"Final Fantasy 7",
"Fire Wii",
"Flintstones",
"Flower Power",
"Foster's Home",
"Friday Night Funkin",
"Friday the 13th",
"Full Metal Alchemist",
"Futurama",
"Gaara",
"Gambit",
"Garfield",
"Gears of War",
"Ghost Busters",
"G I Joe",
"Golden Sun",
"Gorillaz",
"Gothic",
"Grateful Dead",
"Green Bay Packers",
"Grim Adventures of Billy and Mandy",
"GumBall",
"Gundam",
"Hand Drawn",
"Happy Tree Friends",
"Hello Kitty",
"Hell's Kitchen",
"He-Man",
"Heros",
"Hey Arnold",
"HomeStar Runner",
"Hot Wheels",
"The Hundreds",
"Icarly",
"Illusions of Gaia",
"Imports",
"In Betweeners",
"Indiana Jones",
"Indianapolis Colts",
"Insane Clown Posse",
"Its A Me Mario",
"Jay & Silent Bob",
"The Jetsons",
"Jet Set Radio",
"Jimmy Neutron",
"Jimmy Neutron v2",
"Joker",
"Jurassic Park 3",
"Jurassic World",
"Kid Icarus",
"Kingdom Hearts",
"King of the Hill",
"Kirby",
"Kirby Adventures",
"Kiss",
"Korn",
"Lego",
"Lego Batman",
"Leopard OS",
"Lime Wii",
"Limp Bizkit",
"Looney Toons",
"L.A. Rams",
"Lost",
"Luigi v1",
"Luigi v2",
"Luna Chip & Inkie",
"Lupin the Third",
"M & M's",
"Mad World",
"Mad World v2",
"Majoras Mask",
"Manchester United",
"Man Hunt",
"Maria",
"Mario",
"Mario Kart",
"Mario Party 8",
"Martin Abel Art",
"Matrix",
"Matrix Reloaded",
"MegaMan",
"Melancholy of Haruhi",
"Metal Gear Solid",
"Metallica",
"Metroid",
"Metroid Prime",
"Metroid: Samus's Visor",
"Mets",
"MineCraft",
"Minions",
"Minions v2",
"Mist Forest",
"ModMii",
"Monkeys",
"Monopol - Wii",
"Monsters Inc",
"Montreal Canadians",
"Mortal Kombat",
"Mr. Driller",
"Muse",
"My Hero Academia",
"My Little Pony",
"Naruto",
"New Orleans Saints",
"New England Patriots",
"New York Rangers",
"New York Yankees",
"Nightmare B4 Xmas",
"Nightmare Freddy",
"Nights into Dreams",
"Nirvana",
"No More Heros",
"Oakland Raiders",
"Oasis",
"Okami",
"Old School Nintendo",
"Outlaw Star",
"Outer Space",
"Outer Space v2",
"Ozzy",
"Pac Man",
"Paw Patrol",
"Pearl Jam",
"Penguins of Madagascar",
"Phoenix Wright",
"Pikmin",
"Pink Floyd",
"Pink Wii",
"Pinky and The Brain",
"Pirate Skulls",
"Pittsburgh Penguins",
"Pittsburgh Steelers",
"Pizza Tower",
"Popeye",
"Pokemon",
"Predator",
"Princess Ariel v1",
"Princess Ariel v2",
"Princess Ariel v3",
"Psychedelic",
"Punch Out",
"The Punisher",
"Randy Orton",
"Ratchet and Clank",
"Reconnect 24 Blue",
"Reconnect 24 Red",
"Red Wii Motion",
"Regular Show",
"Ren and Stimpy",
"Resident Evil 4",
"Rey Mysterio",
"Rhythm Heaven",
"Rick and Morty",
"Rick and Morty v2",
"Roblox",
"Robot Chicken",
"Rockband 2",
"Rocko's Modern Life",
"Rolling Stones",
"Rondo of Blood",
"Rugrats",
"Saw",
"ScarFace",
"Scooby Doo",
"Secrets of Mana",
"Seinfeld",
"Sendo World",
"Sesame Street",
"Shadow The Hedgehog",
"Shakugan no Shana",
"ShineDown",
"Silver The Hedgehog",
"Smash Brothers Brawl",
"Smokers",
"Snoopy",
"Sonic 3",
"Sonic Frontiers",
"Sonic Riders",
"Sons of Anarchy",
"South Park",
"South Park v2",
"Spawn",
"Spice & Wolf",
"Spiderman",
"SpongeBob",
"SpongeBob v2",
"Squid Billies",
"StarCraft",
"Star Fox Zero",
"Star Gate",
"Star Trek",
"Star Wars",
"Star Wars Unleashed",
"Steel Wii",
"Storms",
"Street Fighter",
"Super Hero Squad",
"Super Mario Brothers 3",
"Super Mario RPG",
"Super Mario Sunshine",
"Super Paper Mario",
"Super Sonic",
"The Simpsons v1",
"The Simpsons v2",
"The Simpsons v3",
"Tails",
"Tamagotchi",
"Tamagotchi v2",
"The Terminator",
"Terra Nigma",
"Thunder Cats",
"Teenage Mutant Ninja Turtles",
"Tenacious D",
"Tom and Jerry",
"Tom and Jerry v2",
"Tomb Raider",
"Toronto Maple Leafs",
"Total Drama Action",
"Toxic Toons",
"Toy Story",
"Toy Story v2",
"Transformers",
"Trials of Mana",
"Tri-Gun",
"Tropical Teal",
"True Blood",
"Ultimate Dark Wii",
"USB Animals",
"Vancouver Canucks",
"Vegeta",
"Vista",
"Wacky Races",
"Wallace and Gromit",
"Walleye",
"Wario Ware",
"Washington Capitals",
"Weapon X",
"Where's Wally",
"White Stripes",
"White Wii",
"Wiid",
"Wii Addict",
"Wii Fit",
"Wii Party",
"Wii Party v2",
"Wii Sports",
"Wii Start Fires",
"Wii U",
"Windows 7",
"Win XP OS",
"Wooden Wii",
"Woody WoodPecker",
"Wolverine",
"Wolverine v2",
"WWE Raw",
"Xbox 360",
"X Men",
"Yoshi",
"Yugi-oh",
"Zelda",
"Zelda: A Link to the Past",
"Zelda: Minish Cap",
"Zelda v2",
"ZombWii"
};
char *Theme_Info[MAXTHEMES] = {
	"ADVTIM-Adventure Time-adventuretime.mym-adventuretime.png-adventuretime.txt",
"RLMSTR-Ahh Real Monsters-realmonsters.mym-realmonsters.png-realmonsters.txt",
"AMDAD1-American Dad-american_dad.mym-american_dad.png-american_dad.txt",
"AMDAD2-American Dad v2-american_dadv2.mym-american_dadv2.png-american_dadv2.txt",
"AMONG1-Among Us v1-amongusv1.mym-amongusv1.png-amongusv1.txt",
"AMONG2-Among Us v2-amongusv2.mym-amongusv2.png-amongusv2.txt",
"ANGBVR-Angry Beavers-angrybeavers.mym-angrybeavers.png-angrybeavers.txt",
"ANML01-Animal Crossing-animal_crossing.mym-animalcrossing.png-animal_crossing.txt",
"ANML02-Animal Crossing v2-animal_crossing_v2.mym-animalcrossingv2.png-animal_crossing_v2.txt",
"APPLE1-Apple-apple.mym-apple.png-apple.txt",
"ATHF01-Aqua Teen Hunger Force-aqua_teen_hunger_force_stage1.mym-ATHF.png-aqua_teen_hunger_force.txt",
"AODRK1-Army of Darkness-army_of_darkness_stage1.mym-army_of_darkness.png-army_of_darkness.txt",
"ARSNFC-Arsenal FC-arsenal_stage1.mym-arsenal.png-arsenal.txt",
"FALCON-Atlanta Falcons-falcons.mym-falcons.png-falcons.txt",
"AVENG1-Avengers-avengers.mym-avengers.png-avengers.txt",
"BACFUT-Back to the Future-back_to_the_future.mym-backtothefuture.png-backtothefuture.txt",
"BKGN01-Bakugan-bakugan.mym-bakugan.png-bakugan.txt",
"BRCLNA-FC Barcelona-barcelona_stage1.mym-barcelona.png-barcelona.txt",
"BATDRI-Battle for Dream Island-battle_4_dream_island.mym-battlefordreamisland.png-battlefordreamisland.txt",
"BTMN01-Batman v1-batman_v1.mym-batmanv1.png-batman_v1.txt",
"BTMN02-Batman v2-batman_v2.mym-batmanv2.png-batman_v2.txt",
"BIGG01-Notorious B.I.G.-biggie_stage1.mym-biggie.png-biggie.txt",
"BILLY1-Billy Mays-billy_mays.mym-billymays.png-billymays.txt",
"BLKGD1-Black Gold-blackgold.mym-blackgold.png-blackgold.txt",
"BLMG01-Black Mage-black_mage.mym-blackmage.png-black_mage.txt",
"BLPR01-Black Pirate-black_pirate.mym-blackpirate.png-black_pirate.txt",
"BLPR02-Black Pirate v2-black_pirate_v2.mym-blackpiratev2.png-black_piratev2.txt",
"BLKSAB-Black Sabbath-blacksabbath.mym-blacksabbath.png-blacksabbath.txt",
"BLCH01-Bleach-bleach.mym-bleach.png-bleach.txt",
"BLUCLU-Blue's Clue's-bluesclues.mym-bluesclues.png-bluesclues.txt",
"BWBETA-Blue Wii Beta-bluewii_beta.mym-bluewii_beta.png-bluewii_beta.txt",
"BOBO01-BoBoBo-bobobo_stage1.mym-bobobo.png-bobobo.txt",
"BDSTS1-Boondock Saints-boondock_saints.mym-boondocksaints.png-boondock_saints.txt",
"BSTRD1-Boston Red Socks-boston.mym-boston_redsocks.png-boston_redsocks.txt",
"BWSR01-Bowser-bowser.mym-bowser.png-bowser.txt",
"BRATZ1-Bratz-bratz.mym-bratz.png-bratz.txt",
"BRLY01-Broly-broly.mym-broly.png-broly.txt",
"BILLS1-Buffalo Bills-bills.mym-buffalo_bills.png-buffalo_bills.txt",
"BUFFY1-Buffy the Vampyr Slayer-buffy.mym-buffy.png-buffy.txt",
"BUSYTN-Busy Town-busytown.mym-busytown.png-busytown.txt",
"CODTY1-Call of Duty-call_of_duty.mym-callofduty.png-call_of_duty.txt",
"CPTCMN-Captain Caveman-caveman.mym-caveman.png-caveman.txt",
"CAR001-Car-car.mym-car.png-car.txt",
"PNTHR1-Carolina Panthers-panthers.mym-carolina_panthers.png-panthers.txt",
"CARS01-Cars-cars_stage1.mym-cars.png-cars.txt",
"CSTLV1-Castlevania-castlevania.mym-castlevania.png-castlevania.txt",
"CATDOG-CatDog-catdog.mym-catdog.png-catdog.txt",
"CELTIC-Celtic FC-celtic.mym-celtic.png-celtic.txt",
"CHNSAW-Chainsaw Man-chainsaw_man.mym-chainsaw_man.png-chainsaw_man.txt",
"CKMO01-Check Mii Out-check_mii_out.mym-check_mii_out.png-check_mii_out.txt",
"BEARS1-Chicago Bears-bears.mym-chicago_bears.png-bears.txt",
"HAWKS1-Chicago Black Hawks-blackhawks.mym-chicago_blackhawks.png-blackhawks.txt",
"BULLS1-Chicago Bulls-bulls.mym-chicago_bulls.png-bulls.txt",
"CHOWDR-Chowder-chowder.mym-chowder.png-chowder.txt",
"XMASSE-Christmas-xmas.mym-xmas.png-xmas.txt",
"CRTRG1-Chrono Trigger-chronotrigger.mym-chronotrigger.png-chronotrigger.txt",
"CLKWK1-Clock Work Orange-clockwork_orange.mym-clockworkorange.png-clockworkorange.txt",
"CLBPN1-Club Penguin-clubpenguin.mym-clubpenguin.png-clubpenguin.txt",
"CD:KND-CodeName: Kids Next Door-knd.mym-knd.png-knd.txt",
"GEASS1-Code Geass-code_geass.mym-codegeass.png-code_geass.txt",
"CONDT1-Conduit-conduit.mym-conduit.png-conduit.txt",
"CONDT2-Conduit v2-conduitv2.mym-conduitv2.png-conduitv2.txt",
"CONST1-Constantine-constantine.mym-constantine.png-constantine.txt",
"CURAGE-Courage-courage.mym-courage.png-courage.txt",
"CRETUR-Creature Cases-creature_cases.mym-creature_cases.png-creature_cases.txt",
"DAISYB-Daisy Blaize-daisy.mym-daisy.png-daisy.txt",
"CWBYS1-Dallas Cowboys-dallas.mym-dallas_cowboys.png-cowboys.txt",
"DANDAN-Dan Da Dan-dandadan.mym-dandadan.png-dandadan.txt",
"DKUB01-Dark Umbra v1-dark_umbra_v1.mym-dark_umbra_v1.png-dark_umbra_v1.txt",
"DKUB02-Dark Umbra v2-dark_umbra_v2.mym-dark_umbra_v2.png-dark_umbra_v2.txt",
"DWEXT1-Dark Wii Extended-darkwii_extended-darkwii_extended.png-darkwii_extended.txt",
"DKWI+1-Dark Wii Plus-darkwii_plus.mym-darkwii_plus.png-darkwii_plus.txt",
"DWORI1-Dark Wii Original-dark_wii_original.mym-darkwiioriginal.png-dark_wii_original.txt",
"DWBL-Dark Wii Blue-dark_wii_blue-darkwiiblue.png-dark_wii_blue.txt",
"DWGR-Dark Wii Green-dark_wii_green-darkwiigreen.png-dark_wii_green.txt",
"DWOR-Dark Wii Orange-dark_wii_orange-darkwiiorange.png-dark_wii_orange.txt",
"DWPK-Dark Wii Pink-dark_wii_pink-darkwiipink.png-dark_wii_pink.txt",
"DWPR-Dark Wii Purple-dark_wii_purple-darkwiipurple.png-dark_wii_purple.txt",
"DWRD-Dark Wii Red-dark_wii_red-darkwiired.png-dark_wii_red.txt",
"DWWH-Dark Wii White-dark_wii_white-darkwiiwhite.png-dark_wii_white.txt",
"DWYL-Dark Wii Yellow-dark_wii_yellow-darkwiiyellow.png-dark_wii_yellow.txt",
"DKWSCB-Dark Wii SE-darkwii_SE.mym-dark_scooby.png-dark_scooby.txt",
"DNOTE1-Death Note-deathnote.mym-deathnote.png-deathnote.txt",
"DMNSLR-Demon Slayer-demonslayer.mym-demonslayer.png-demonslayer.txt",
"DKLOK1-Deth Klok-deth_klok.mym-dethklok.png-deth_klok.txt",
"LIONS1-Detroit Lions-lions_stage1.mym-detroit_lions.png-lions.txt",
"DEXLAB-Dexter's Laboratory-dexterslab.mym-dexters_lab.png-dexterslab.txt",
"DIABL1-Diablo 3-diablo_3.mym-diablo_3.png-diablo_3.txt",
"DSCRD1-Discord-discord.mym-discord.png-discord.txt",
"DGMN01-Dog Man-dogman.mym-dogman.png-dogman.txt",
"DOLPH1-Dolphins-dolphins.mym-dolphins.png-dolphins.txt",
"DBLZ01-Dragon Ball Z v1-dragon_ball_z_v1.mym-dragonballzv1.png-dragon_ball_z_v1.txt",
"DBLZ02-Dragon Ball Z v2-dragon_ball_z_v2.mym-dragonballzv2.png-dragon_ball_z_v2.txt",
"DRWTGR-Drawn Together-drawntogether.mym-drawntogether.png-drawntogether.txt",
"DRWHO1-Dr Who-dr_who.mym-drwho.png-dr_who.txt",
"DUKES1-Dukes of Hazzard-dukes_stage1.mym-dukes.png-dukes.txt",
"DGENX1-De-Generation X-dx_stage1.mym-dx.png-dx.txt",
"EGLES1-Eagles-eagles_stage1.mym-eagles.png-eagles.txt",
"ETHBD1-Earth Bound-earth_bound.mym-earthbound.png-earth_bound.txt",
"ETHBD2-Earth Bound v2-earth_boundv2.mym-earthboundv2.png-earth_boundv2.txt",
"ETHBD3-Earth Bound v3-earthboundv3.mym-earthboundv3.png-earth_boundv3.txt",
"EDEDDY-Ed, Edd, n' Eddy-ededdeddy.mym-ededdeddy.png-ededdeddy.txt",
"EMOBL1-Emo Blue-emoblue.mym-emoblue.png-emoblue.txt",
"EMOGR1-Emo Green-emogreen.mym-emogreen.png-emogreen.txt",
"EMOPK1-Emo Pink-emopink.mym-emopink.png-emopink.txt",
"EMOPR1-Emo Purple-emopurple.mym-emopurple.png-emopurple.txt",
"EMORD1-Emo Red-emored.mym-emored.png-emored.txt",
"EVDED1-Evil Dead-evil_dead.mym-evildead.png-evil_dead.txt",
"EXBOT1-Excite Bots-excite_bots.mym-excitebots.png-excite_bots.txt",
"EYES01-Eyes-eyes.mym-eyes.png-eyes.txt",
"FODDP1-Fairly Odd Parents-fairly_odd_parents_stage1.mym-fairlyoddparents.png-fairlyoddparents.txt",
"FMGUY1-Family Guy-family_guy.mym-familyguy.png-family_guy.txt",
"FAN4V1-Fantastic Four-fantasticfour.mym-fantasticfour.png-fantasticfour.txt",
"FANTA1-Fantasy-fantasy.mym-fantasy.png-fantasy.txt",
"FATALB-Fat Albert-fatalbert.mym-fatalbert.png-fatalbert.txt",
"FELIX1-Felix the Cat-felix.mym-felix.png-felix.txt",
"FCLUB1-Fight Club-fight_club.mym-fightclub.png-fight_club.txt",
"FFVII1-Final Fantasy 7-final_fantasy_7.mym-finalfantasy7.png-final_fantasy_7.txt",
"FIRE01-Fire Wii-fire_wii.mym-firewii.png-fire_wii.txt",
"FLINTS-The Flintstones-flintstones.mym-flintstones.png-flintstones.txt",
"FLOPO1-Flower Power-flower_power_stage1.mym-flowerpower.png-flowerpower.txt",
"FOSTER-Foster's Home-fosters_home.mym-fosters_home.png-fosters_home.txt",
"FNFNK1-Friday Night Funkin-friday_night_funkin.mym-fridaynightfunkin.png-fridaynightfunkin.txt",
"F13TH1-Friday the 13th-friday_the_13th_stage1.mym-fridaythe13th.png-fridaythe13th.txt",
"FMTL-Full Metal Alchemist-full_metal_alchemist-fullmetalalchemist.png-full_metal_alchemist.txt",
"FUTUR1-Futurama-futurama.mym-futurama.png-futurama.txt",
"GAARA1-Gaara-gaara.mym-gaara.png-gaara.txt",
"GAMBIT-Gambit-gambit_stage1.mym-gambit.png-gambit.txt",
"GRFLD1-Garfield-garfield.mym-garfield.png-garfield.txt",
"GOWAR1-Gears of War-gears_of_war.mym-gearsofwar.png-gears_of_war.txt",
"GBUST1-Ghost Busters-ghost_busters.mym-ghostbusters.png-ghost_busters.txt",
"GIJOE1-G I Joe-gijoe.mym-gijoe.png-gijoe.txt",
"GSUN01-Golden Sun-golden_sun.mym-goldensun.png-golden_sun.txt",
"GORILA-Gorillaz-gorillaz.mym-gorillaz.png-gorillaz.txt",
"GOTH01-Gothic-gothic.mym-gothic.png-gothic.txt",
"GRTFL1-Grateful Dead-grateful_dead_stage1.mym-gratefuldead.png-gratefuldead.txt",
"PCKRS1-Green Bay Packers-packers_stage1.mym-greenbay_packers.png-packers.txt",
"GABLMD-Grim Adventures of Billy and Mandy-grim.mym-grim.png-grim.txt",
"GUMBLL-GumBall-gumball.mym-gumball.png-gumball.txt",
"GUNDAM-Gundam-gundam.mym-gundam.png-gundam.txt",
"HDRAW1-Hand Drawn-hand_drawn.mym-handdrawn.png-hand_drawn.txt",
"HAPYTF-Happy Tree Friends-treefriends.mym-treefriends.png-treefriends.txt",
"HKITY1-Hello Kitty-hello_kitty.mym-hellokitty.png-hello_kitty.txt",
"HELLK1-Hell's Kitchen-hellskitchen.mym-hellskitchen.png-hellskitchen.txt",
"HEMAN1-He-Man-he-man_stage1.mym-heman.png-heman.txt",
"HEROS1-Heros-heros.mym-heros.png-heros.txt",
"ARMOLD-Hey Arnold-arnold.mym-arnold.png-arnold.txt",
"HMESTR-HomeStar Runner-homestar.mym-homestar.png-homestar.txt",
"WHEEL1-Hot Wheels-hot_wheels.mym-hot_wheels.png-hot_wheels.txt",
"HNDRD1-The Hundreds-hundreds.mym-hundreds.png-hundreds.txt",
"ICARLY-Icarly-icarly.mym-icarly.png-icarly.txt",
"ILLOG1-Illusions of Gaia-illusionsofgaia.mym-illusionsofgaia.png-illusionsofgaia.txt",
"IMPOR1-Imports-imports.mym-imports.png-imports.txt",
"INBET1-In Betweeners-in_betweeners.mym-inbetweeners.png-in_betweeners.txt",
"INDYJO-Indiana Jones-indianajones.mym-indianajones.png-indianajones.txt",
"COLTS1-Indianapolis Colts-colts.mym-colts.png-colts.txt",
"ICP001-Insane Clown Posse-insane_clown_posse.mym-icp.png-insane_clown_posse.txt",
"IMMAR1-Its A Me Mario-itsamemario.mym-itsamemario.png-itsamemario.txt",
"JNSBOB-Jay & Silent Bob-jaybob_stage1.mym-jaybob.png-jaybob.txt",
"JETSON-The Jetsons-jetsons.mym-jetsons.png-jetsons.txt",
"JSRAD1-Jet Set Radio-jetsetradio.mym-jetsetradio.png-jetsetradio.txt",
"JNUTR1-Jimmy Neutron-jimmyneutron.mym-jimmyneutron.png-jimmyneutron.txt",
"JNUTR2-Jimmy Neutron v2-jimmyneutronv2.mym-jimmyneutronv2.png-jimmyneutronv2.txt",
"JOKER1-Joker-joker_stage1.mym-joker.png-joker.txt",
"JRPRK1-Jurassic Park 3-jurassic_park_3.mym-jurassicpark3.png-jurassic_park_3.txt",
"JURWLD-Jurassic World-jurassicworld.mym-jurassicworld.png-jurassicworld.txt",
"KDICR1-Kid Icarus-kidicarus.mym-kidicarus.png-kidicarus.txt",
"KHRT01-Kingdom Hearts-kingdom_hearts.mym-kingdomhearts.png-kingdom_hearts.txt",
"KOTHV1-King of the Hill-kingofthehill.mym-kingofthehill.png-kingofthehill.txt",
"KIRBY1-Kirby-kirby.mym-kirby.png-kirby.txt",
"KIRBY2-Kirby Adventures-kirbyadventures.mym-kirbyadventures.png-kirbyadventures.txt",
"KISS01-Kiss-kiss_stage1.mym-kiss.png-kiss.txt",
"KORN01-Korn-korn.mym-korn.png-korn.txt",
"LEGO01-Lego-lego.mym-lego.png-lego.txt",
"LGOBTM-Lego Batman-legobatman.mym-legobatman.png-legobatman.txt",
"LEOPA1-Leopard OS-leopard_os.mym-leopardos.png-leopard_os.txt",
"LIME01-Lime Wii-lime_wii.mym-limewii.png-lime_wii.txt",
"LMPBIZ-Limp Bizkit-limpbizkit.mym-limpbizkit.png-limpbizkit.txt",
"LTOON1-Looney Toons-looney_toons.mym-looneytoons.png-looney_toons.txt",
"LARAMS-L.A. Rams-larams.mym-larams.png-larams.txt",
"LOST01-Lost-lost.mym-lost.png-lost.txt",
"LUIGI1-Luigi v1-luigi_v1.mym-luigi.png-luigi.txt",
"LUIGI2-Luigi v2-luigi_v2_stage1.mym-luigiv2.png-luigiv2.txt",
"LACPIE-Luna Chip & Inkie-luna_chip_inkie.mym-luna_chip_inkie.png-luna_chip_inkie.txt",
"LUPIN3-Lupin the Third-lupin.mym-lupin.png-lupin.txt",
"MNMS01-M & M's-mms.mym-m&ms.png-mms.txt",
"MWRLD1-Mad World-mad_world.mym-madworld.png-mad_world.txt",
"MWRLD2-Mad World v2-mad_world2.mym-mad_world_v2.png-mad_world_v2.txt",
"MAMSK1-Majoras Mask-majoras_mask.mym-majorasmask.png-majoras_mask.txt",
"UNITED-Manchester United-united_stage1.mym-united.png-united.txt",
"MNHNT1-Man Hunt-manhunt_stage1.mym-manhunt.png-manhunt.txt",
"MARIA1-Maria-maria_stage1.mym-maria.png-maria.txt",
"MARIO2-Mario-mario.mym-mariojeb.png-mario.txt",
"MKART1-Mario Kart-mario_kart.mym-mariokart.png-mario_kart.txt",
"PARTY8-Mario Party 8-marioparty8.mym-marioparty8.png-marioparty8.txt",
"MABEL1-Martin Abel Art-martin_abel.mym-martin_abel.png-martin_abel.txt",
"MATRX1-Matrix-matrix.mym-matrix.png-matrix.txt",
"MATRX2-Matrix Reloaded-matrix_reloaded.mym-matrixreloaded.png-matrix_reloaded.txt",
"MEGMN1-MegaMan-megaman.mym-megaman.png-megaman.txt",
"MOHAR1-Melancholy of Haruhi-melonofharuhi_stage1.mym-melonofharuhi.png-melonofharuhi.txt",
"MGSOL1-Metal Gear Solid-metal_gear_solid.mym-metalgearsolid.png-metal_gear_solid.txt",
"MTLCA1-Metallica-metallica.mym-metallica.png-metallica.txt",
"MTROD1-Metroid-metroid.mym-metroid.png-metroid.txt",
"METPR1-Metroid Prime-metroid_prime.mym-metroid_prime.png-metroid_prime.txt",
"MTDSV1-Metroid: Samus's Visor-metroid_samus_visor.mym-metroid_samusvisor.png-metroid_samusvisor.txt",
"METS01-Mets-mets.mym-mets.png-mets.txt",
"MINECR-MineCraft-minecraft.mym-minecraft.png-minecraft.txt",
"MINION-Minions-minions.mym-minions.png-minions.txt",
"MNION2-Minions v2-minionsv2.mym-minionsv2.png-minionsv2.txt",
"MISTF1-Mist Forest-mistforest.mym-mistforest.png-mistforest.txt",
"MODMII-ModMii-modmii.mym-modmii.png-modmii.txt",
"MONKEY-Monkeys-monkeys_stage1.mym-monkeys.png-monkeys.txt",
"MONOW1-Monopol - Wii-monopoly.mym-monopoly.png-monopoly.txt",
"MONSTR-Monsters Inc-monsters_inc.mym-monsters_inc.png-monsters_inc.txt",
"CANAD1-Montreal Canadians-canadians.mym-canadians.png-canadians.txt",
"MKOMB1-Mortal Kombat-mortal_kombat.mym-mortalkombat.png-mortal_kombat.txt",
"MRDRIL-Mr. Driller-mrdriller.mym-mrdriller.png-mrdriller.txt",
"MUSE01-Muse-muse.mym-muse.png-muse.txt",
"MYHERO-My Hero Academia-myhero.mym-myhero.png-myhero.txt",
"MYPONY-My Little Pony-poni.mym-poni.png-poni.txt",
"NARTO1-Naruto-naruto.mym-naruto.png-naruto.txt",
"SAINT1-New Orleans Saints-saints_stage1.mym-saints.png-saints.txt",
"NEPAT1-New England Patriots-patriots_stage1.mym-patriots.png-patriots.txt",
"RANGR1-New York Rangers-rangers.mym-rangers.png-rangers.txt",
"YANKE1-New York Yankees-yankees.mym-yankees.png-yankees.txt",
"NMB4X1-Nightmare B4 Xmas-nightmare_b4_xmas.mym-nightmareb4xmas.png-nightmare_b4_xmas.txt",
"FREDDy-Nightmare Freddy-freddy.mym-freddy.png-freddy.txt",
"NIDRM1-Nights into Dreams-nightsintodreams.mym-nightsintodreams.png-nightsintodreams.txt",
"NRVNA1-Nirvana-nirvana_stage1.mym-nirvana.png-nirvana.txt",
"NOMRH1-No More Heros-nomoreheroes.mym-nomoreheros.png-nomoreheros.txt",
"RAIDR1-Oakland Raiders-raiders_stage1.mym-raiders.png-raiders.txt",
"OASIS1-Oasis-oasis_stage1.mym-oasis.png-oasis.txt",
"OKAMI1-Okami-okami.mym-okami.png-okami.txt",
"OSNIN1-Old School Nintendo-old_school_nintendo.mym-oldschoolnintendo.png-old_school_nintendo.txt",
"OTLWS1-Outlaw Star-outlawstar.mym-outlawstar.png-outlawstar.txt",
"SPACE1-Outer Space-outerspace.mym-outerspace.png-outerspace.txt",
"SPACE2-Outer Space v2-spacev2.mym-spacev2.png-spacev2.txt",
"OZZY01-Ozzy-ozzy.mym-ozzy.png-ozzy.txt",
"PACMAN-Pac Man-pacman.mym-pacman.png-pacman.txt",
"PWPTRL-Paw Patrol-pawpatrol.mym-pawpatrol.png-pawpatrol.txt",
"PLJAM1-Pearl Jam-pearl_jam.mym-pearl_jam.png-pearl_jam.txt",
"POMAD1-Penguins of Madagascar-penguins_of_madagascar_stage1.mym-penguinsofmad.png-penguinsofmad.txt",
"PHWRT1-Phoenix Wright-phoenixwright.mym-phoenixwright.png-phoenixwright.txt",
"PIKMN1-Pikmin-pikmin.mym-pikmin.png-pikmin.txt",
"PKFLD1-Pink Floyd-pinkfloyd_stage1.mym-pinkfloyd.png-pinkfloyd.txt",
"PNKWI1-Pink Wii-pinkwii.mym-pinkwii.png-pinkwii.txt",
"PNKBRN-Pinky and The Brain-pinkybrain.mym-pinkybrain.png-pinkybrain.txt",
"PRSKL1-Pirate Skulls-pirateskulls_stage1.mym-piratesskulls.png-pirateskulls.txt",
"PENGUN-Pittsburgh Penguins-penguins.mym-penguins.png-penguins.txt",
"STELR1-Pittsburgh Steelers-steelers_stage1.mym-steelers.png-steelers.txt",
"PIZTR1-Pizza Tower-pizzatower.mym-pizzatower.png-pizzatower.txt",
"POPEYE-Popeye-popeye.mym-popeye.png-popeye.txt",
"POKEMN-Pokemon-pokemon.mym-pokemon.png-pokemon.txt",
"PREDR1-Predator-predator.mym-predator.png-predator.txt",
"PARIE1-Princess Ariel v1-princess_ariel_v1.mym-princess_ariel_v1.png-princess_ariel_v1.txt",
"PARIE2-Princess Ariel v2-princess_ariel_v2.mym-princess_ariel_v2.png-princess_ariel_v2.txt",
"PARIE3-Princess Ariel v3-princess_ariel_v3.mym-princess_ariel_v3.png-princess_ariel_v3.txt",
"PSYCO1-Psychedelic-psychedelic.mym-psycedelic.png-psychedelic.txt",
"PNOUT1-Punch Out-punch_out.mym-punchout.png-punch_out.txt",
"PUNSH1-The Punisher-punisher_stage1.mym-punisher.png-punisher.txt",
"ORTON1-Randy Orton-randy_orton.mym-randyorton.png-randyorton.txt",
"RCLNK1-Ratchet and Clank-ratchet_and_clank.mym-ratchetnclank.png-ratchet_and_clank.txt",
"RC2402-Reconnect 24 Blue-rc24_blue.mym-rc24blue.png-rc24_blue.txt",
"RC2401-Reconnect 24 Red-rc24_red.mym-rc24red.png-rc24_red.txt",
"REDMO1-Red Wii Motion-redwiimotion.mym-redwiimotion.png-redwiimotion.txt",
"REGSHW-Regular Show-regularshow.mym-regularshow.png-regularshow.txt",
"RENSTM-Ren and Stimpy-renstimpy.mym-renstimpy.png-renstimpy.txt",
"RESEVE-Resident Evil 4-re4.mym-re4.png-re4.txt",
"RMYST1-Rey Mysterio-rey_mysterio.mym-rey_mysterio.png-rey_mysterio.txt",
"RHYTH1-Rhythm Heaven-rhythm_heaven.mym-rhythmheaven.png-rhythmheaven.txt",
"RMORT1-Rick and Morty-ricknmorty.mym-ricknmorty.png-ricknmorty.txt",
"RMORT2-Rick and Morty v2-ricknmortyv2.mym-ricknmortyv2.png-ricknmortyv2.txt",
"ROBLOX-Roblox-roblox.mym-roblox.png-roblox.txt",
"RCHCK1-Robot Chicken-robot_chicken.mym-robotchicken.png-robot_chicken.txt",
"RBAND1-Rockband 2-rockband_2.mym-rockband2.png-rockband_2.txt",
"ROCKOS-Rocko's Modern Life-rockosmodernlife.mym-rockosmodernlife.png-rockosmodernlife.txt",
"STONES-Rolling Stones-rolling_stones.mym-rollingstones.png-rollingstones.txt",
"RBLOD1-Rondo of Blood-rondo_of_blood.mym-rondo_of_blood.png-rondo_of_blood.txt",
"RUGRAT-Rugrats-rugrats.mym-rugrats.png-rugrats.txt",
"SAW001-Saw-saw.mym-saw.png-saw.txt",
"SCRFC1-ScarFace-scarface.mym-scarface.png-scarface.txt",
"SCOOBY-Scooby Doo-scoobydoo.mym-scoobydoo.png-scoobydoo.txt",
"SECOM1-Secrets of Mana-secretsofmana.mym-secretsofmana.png-secretsofmana.txt",
"SEINF1-Seinfeld-Seinfeld.mym-seinfeld.png-Seinfeld.txt",
"SENDO1-Sendo World-sendo.mym-sendo.png-sendo.txt",
"SESAME-Sesame Street-sesamestreet.mym-sesamestreet.png-sesamestreet.txt",
"SHADH1-Shadow The Hedgehog-shadow_the_hedgehog.mym-shadowthehedgehog.png-shadow_the_hedgehog.txt",
"SHANA1-Shakugan no Shana-shana_stage1.mym-shana.png-shana.txt",
"SHNDWN-ShineDown-shinedown_stage1.mym-shinedown.png-shinedown.txt",
"SILVH1-Silver The Hedgehog-silver_the_hedgehog.mym-silverthehedgehog.png-silver_the_hedgehog.txt",
"SMASH1-Smash Brothers Brawl-smash_brothers_brawl.mym-smashbros.png-smashbros.txt",
"SMOKE1-Smokers-smokers.mym-smokers.png-smokers.txt",
"SNOOP1-Snoopy-snoopy.mym-snoopy.png-snoopy.txt",
"SONIC3-Sonic 3-sonic3.mym-sonic3.png-sonic3.txt",
"SNCFT1-Sonic Frontiers-sonicfrontiers.mym-sonicfrontiers.png-sonicfrontiers.txt",
"SNCRD1-Sonic Riders-sonicriders.mym-sonicriders.png-sonicriders.txt",
"SONOA1-Sons of Anarchy-sonsofanarchy_stage1.mym-sonsofanarchy.png-sonsofanarchy.txt",
"STHPK1-South Park-southpark.mym-southpark.png-southpark.txt",
"STHPK2-South Park v2-southparkv2.mym-southparkv2.png-southparkv2.txt",
"SPAWN1-Spawn-spawn.mym-spawn.png-spawn.txt",
"SPICE1-Spice & Wolf-spiceandwolf.mym-spiceandwolf.png-spiceandwolf.txt",
"SPDMN1-Spiderman-Spiderman.mym-spiderman.png-Spiderman.txt",
"SPONG1-SpongeBob-spongebob.mym-spongebob.png-spongebob.txt",
"SPONG2-SpongeBob v2-spongebobv2.mym-spongebobv2.png-spongebobv2.txt",
"SQUBL1-Squid Billies-squid_billies_stage1.mym-squidbillies.png-squidbillies.txt",
"STCFT1-StarCraft-star_craft.mym-starcraft.png-starcraft.txt",
"STARFX-Star Fox Zero-starfoxzero.mym-starfoxzero.png-starfoxzero.txt",
"STGTE1-Star Gate-star_gate.mym-stargate.png-stargate.txt",
"STRTRK-Star Trek-startrek.mym-startrek.png-startrek.txt",
"STWRS1-Star Wars-star_wars.mym-starwars.png-starwars.txt",
"STWRS2-Star Wars Unleashed-star_wars_unleashed.mym-starwarsunleashed.png-starwarsunleashed.txt",
"STWII1-Steel Wii-steel_wii.mym-steelwii.png-steelwii.txt",
"STRM-Storms-storms-storms.png-storms.txt",
"STRFT1-Street Fighter-street_fighter.mym-streetfighter.png-streetfighter.txt",
"SHSQU1-Super Hero Squad-super_hero_squad.mym-superherosquad.png-super_hero_squad.txt",
"SMARB3-Super Mario Brothers 3-supermariobros3.mym-supermariobros3.png-supermariobros3.txt",
"SMRPG1-Super Mario RPG-super_mario_RPG.mym-supermariorpg.png-super_mario_RPG.txt",
"SMSUN1-Super Mario Sunshine-supermariosunshine.mym-supermariosunshine.png-supermariosunshine.txt",
"SPAPM1-Super Paper Mario-superpapermario.mym-superpapermario.png-superpapermario.txt",
"SSONI1-Super Sonic-super_sonic.mym-supersonic.png-super_sonic.txt",
"SIMPS1-The Simpsons v1-the_simpsons_v1.mym-simpsons_v1.png-the_simpsons_v1.txt",
"SIMPS2-The Simpsons v2-the_simpsons_v2.mym-simpsons_v2.png-the_simpsons_v2.txt",
"SIMPS3-The Simpsons v3-the_simpsons_v3.mym-simpsons_v3.png-the_simpsons_v3.txt",
"TAILS1-Tails-tails_stage1.mym-tails.png-tails.txt",
"TAMAGO-Tamagotchi-tamagotchi.mym-tamagotchi.png-tamagotchi.txt",
"TAMAG2-Tamagotchi v2-tamagotchiv2.mym-tamagotchiv2.png-tamagotchiv2.txt",
"TERMR1-The Terminator-terminator.mym-terminator.png-terminator.txt",
"TERNG1-Terra Nigma-terranigma.mym-terranigma.png-terranigma.txt",
"TCATS1-Thunder Cats-thunder_cats.mym-thundercats.png-thunder_cats.txt",
"TMNT01-Teenage Mutant Ninja Turtles-tmnt.mym-tmnt.png-tmnt.txt",
"TENACD-Tenacious D-tenaciousD.mym-tenaciousD.png-tenaciousD.txt",
"TOMJER-Tom and Jerry-tomandjerry.mym-tomandjerry.png-tomandjerry.txt",
"TMJER2-Tom and Jerry v2-tomandjerryv2.mym-tomandjerryv2.png-tomandjerryv2.txt",
"TRAID1-Tomb Raider-tomb_raider.mym-tombraider.png-tomb_raider.txt",
"LEAFS1-Toronto Maple Leafs-leafs.mym-leafs.png-leafs.txt",
"TOTDR1-Total Drama Action-totaldrama_stage1.mym-totaldrama.png-totaldrama.txt",
"TTOON1-Toxic Toons-toxic_toons.mym-toxictoons.png-toxictoons.txt",
"TOYST1-Toy Story-toystory.mym-toystory.png-toystory.txt",
"TOYST2-Toy Story v2-toystoryv2.mym-toystoryv2.png-toystoryv2.txt",
"TRANS1-Transformers-transformers.mym-transformers.png-transformers.txt",
"TRLOM1-Trials of Mana-trialsofmana.mym-trialsofmana.png-trialsofmana.txt",
"TRGUN1-Tri-Gun-tri-gun.mym-trigun.png-trigun.txt",
"TRPTL1-Tropical Teal-tropicalteal.mym-tropicalteal.png-tropicalteal.txt",
"TBLOD1-True Blood-true_blood.mym-trueblood.png-true_blood.txt",
"UDWII1-Ultimate Dark Wii-ultimate_dark_wii_stage1.mym-ultimatedarkwii.png-ultimatedarkwii.txt",
"USBANI-USB Animals-usbanimals.mym-usbanimals.png-usbanimals.txt",
"CANUCK-Vancouver Canucks-canucks.mym-canucks.png-canucks.txt",
"VEGET1-Vegeta-vegeta.mym-vegeta.png-vegeta.txt",
"VISTA1-Vista-vista.mym-vista.png-vista.txt",
"WACKY1-Wacky Races-wackyraces.mym-wackyraces.png-wackyraces.txt",
"WALACE-Wallace and Gromit-wallacegromit.mym-wallacegromit.png-wallacegromit.txt",
"WALEY1-Walleye-walleye_stage1.mym-walleye.png-walleye.txt",
"WARIO1-Wario Ware-wario_ware.mym-warioware.png-warioware.txt",
"CAPTLS-Washington Capitals-capitals.mym-capitals.png-capitals.txt",
"WEAPNX-Weapon X-weaponx.mym-weaponx.png-weaponx.txt",
"WWALDO-Where's Wally-whereswally.mym-whereswally.png-whereswally.txt",
"WSTRI1-White Stripes-white_stripes_stage1.mym-whitestripes.png-whitestripes.txt",
"WHITE1-White Wii-white_wii.mym-whitewii.png-whitewii.txt",
"WIID01-Wiid-wiid.mym-wiid.png-wiid.txt",
"WIIADC-Wii Addict-wiiadict.mym-wiiadict.png-wiiadict.txt",
"WIFIT1-Wii Fit-wii_fit.mym-wiifit.png-wiifit.txt",
"WIIPT1-Wii Party-wiiparty.mym-wiiparty.png-wiiparty.txt",
"WIIPT2-Wii Party v2-wiipartyv2.mym-wiipartyv2.png-wiipartyv2.txt",
"WSPOR1-Wii Sports-wii_sports.mym-wiisports.png-wiisports.txt",
"WIISTR-Wii Start Fires-wiistartfires.mym-wiistartfires.png-wiistartfires.txt",
"WIIU01-Wii U-wii_u.mym-wiiu.png-wiiu.txt",
"WIN701-Windows 7-windows7.mym-windows7.png-windows7.txt",
"WINXP1-Win XP OS-win_xp_os.mym-windowsxp.png-win_xp_os.txt",
"WOODWI-Wooden Wii-woodwii.mym-woodwii.png-woodwii.txt",
"WOODYP-Woody WoodPecker-woody.mym-woodywoodpecker.png-woodywoodpecker.txt",
"WOLVE1-Wolverine-wolverine.mym-wolverine.png-wolverine.txt",
"WOLVE2-Wolverine v2-wolverinev2.mym-wolverinev2.png-wolverinev2.txt",
"WWERW1-WWE Raw-wwe_raw.mym-wweraw.png-wweraw.txt",
"XBOX01-Xbox 360-xbox360.mym-xbox360.png-xbox360.txt",
"XMENV1-X Men-xmen.mym-xmen.png-xmen.txt",
"GYOSHI-Yoshi-yoshi.mym-yoshi.png-yoshi.txt",
"YUGIO1-Yugi-oh-yugioh.mym-yugioh.png-yugioh.txt",
"ZELDA1-Zelda-zelda.mym-zelda.png-zelda.txt",
"ZELDA2-Zelda: A Link to the Past-zelda2.mym-zelda2.png-zelda2.txt",
"ZELDA3-Zelda: Minish Cap-minishcap.mym-minishcap.png-minishcap.txt",
"ZELDA4-Zelda v2-zelda_v4.mym-zelda_v4.png-zelda_v4.txt",
"ZOMB01-ZombWii-zombwii.mym-zombwii.png-zombwii.txt"
};

char *Theme_Mym_File[MAXTHEMES] = {
"adventuretime.mym",
"realmonsters.mym",
"american_dad.mym",
"american_dadv2.mym",
"amongusv1.mym",
"amongusv2.mym",
"angrybeavers.mym",
"animal_crossing.mym",
"animal_crossing_v2.mym",
"apple.mym",
"aqua_teen_hunger_force_stage1.mym",
"army_of_darkness_stage1.mym",
"arsenal_stage1.mym",
"falcons.mym",
"avengers.mym",
"back_to_the_future.mym",
"bakugan.mym",
"barcelona_stage1.mym",
"battle_4_dream_island.mym",
"batman_v1.mym",
"batman_v2.mym",
"biggie_stage1.mym",
"billy_mays.mym",
"blackgold.mym",
"black_mage.mym",
"black_pirate.mym",
"black_pirate_v2.mym",
"blacksabbath.mym",
"bleach.mym",
"bluesclues.mym",
"bluewii_beta.mym",
"bobobo_stage1.mym",
"boondock_saints.mym",
"boston.mym",
"bowser.mym",
"bratz.mym",
"broly.mym",
"bills.mym",
"buffy.mym",
"busytown.mym",
"call_of_duty.mym",
"caveman.mym",
"car.mym",
"panthers.mym",
"cars_stage1.mym",
"castlevania.mym",
"catdog.mym",
"celtic.mym",
"chainsaw_man.mym",
"check_mii_out.mym",
"bears.mym",
"blackhawks.mym",
"bulls.mym",
"chowder.mym",
"xmas.mym",
"chronotrigger.mym",
"clockwork_orange.mym",
"clubpenguin.mym",
"knd.mym",
"code_geass.mym",
"conduit.mym",
"conduitv2.mym",
"constantine.mym",
"courage.mym",
"creature_cases.mym",
"daisy.mym",
"dallas.mym",
"dandadan.mym",
"dark_umbra_v1.mym",
"dark_umbra_v2.mym",
"darkwii_extended",
"darkwii_plus.mym",
"dark_wii_original.mym",
"dark_wii_blue",
"dark_wii_green",
"dark_wii_orange",
"dark_wii_pink",
"dark_wii_purple",
"dark_wii_red",
"dark_wii_white",
"dark_wii_yellow",
"darkwii_SE.mym",
"deathnote.mym",
"demonslayer.mym",
"deth_klok.mym",
"lions_stage1.mym",
"dexterslab.mym",
"diablo_3.mym",
"discord.mym",
"dogman.mym",
"dolphins.mym",
"dragon_ball_z_v1.mym",
"dragon_ball_z_v2.mym",
"drawntogether.mym",
"dr_who.mym",
"dukes_stage1.mym",
"dx_stage1.mym",
"eagles_stage1.mym",
"earth_bound.mym",
"earth_boundv2.mym",
"earthboundv3.mym",
"ededdeddy.mym",
"emoblue.mym",
"emogreen.mym",
"emopink.mym",
"emopurple.mym",
"emored.mym",
"evil_dead.mym",
"excite_bots.mym",
"eyes.mym",
"fairly_odd_parents_stage1.mym",
"family_guy.mym",
"fantasticfour.mym",
"fantasy.mym",
"fatalbert.mym",
"felix.mym",
"fight_club.mym",
"final_fantasy_7.mym",
"fire_wii.mym",
"flintstones.mym",
"flower_power_stage1.mym",
"fosters_home.mym",
"friday_night_funkin.mym",
"friday_the_13th_stage1.mym",
"full_metal_alchemist",
"futurama.mym",
"gaara.mym",
"gambit_stage1.mym",
"garfield.mym",
"gears_of_war.mym",
"ghost_busters.mym",
"gijoe.mym",
"golden_sun.mym",
"gorillaz.mym",
"gothic.mym",
"grateful_dead_stage1.mym",
"packers_stage1.mym",
"grim.mym",
"gumball.mym",
"gundam.mym",
"hand_drawn.mym",
"treefriends.mym",
"hello_kitty.mym",
"hellskitchen.mym",
"he-man_stage1.mym",
"heros.mym",
"arnold.mym",
"homestar.mym",
"hot_wheels.mym",
"hundreds.mym",
"icarly.mym",
"illusionsofgaia.mym",
"imports.mym",
"in_betweeners.mym",
"indianajones.mym",
"colts.mym",
"insane_clown_posse.mym",
"itsamemario.mym",
"jaybob_stage1.mym",
"jetsons.mym",
"jetsetradio.mym",
"jimmyneutron.mym",
"jimmyneutronv2.mym",
"joker_stage1.mym",
"jurassic_park_3.mym",
"jurassicworld.mym",
"kidicarus.mym",
"kingdom_hearts.mym",
"kingofthehill.mym",
"kirby.mym",
"kirbyadventures.mym",
"kiss_stage1.mym",
"korn.mym",
"lego.mym",
"legobatman.mym",
"leopard_os.mym",
"lime_wii.mym",
"limpbizkit.mym",
"looney_toons.mym",
"larams.mym",
"lost.mym",
"luigi_v1.mym",
"luigi_v2_stage1.mym",
"luna_chip_inkie.mym",
"lupin.mym",
"mms.mym",
"mad_world.mym",
"mad_world2.mym",
"majoras_mask.mym",
"united_stage1.mym",
"manhunt_stage1.mym",
"maria_stage1.mym",
"mario.mym",
"mario_kart.mym",
"marioparty8.mym",
"martin_abel.mym",
"matrix.mym",
"matrix_reloaded.mym",
"megaman.mym",
"melonofharuhi_stage1.mym",
"metal_gear_solid.mym",
"metallica.mym",
"metroid.mym",
"metroid_prime.mym",
"metroid_samus_visor.mym",
"mets.mym",
"minecraft.mym",
"minions.mym",
"minionsv2.mym",
"mistforest.mym",
"modmii.mym",
"monkeys_stage1.mym",
"monopoly.mym",
"monsters_inc.mym",
"canadians.mym",
"mortal_kombat.mym",
"mrdriller.mym",
"muse.mym",
"myhero.mym",
"poni.mym",
"naruto.mym",
"saints_stage1.mym",
"patriots_stage1.mym",
"rangers.mym",
"yankees.mym",
"nightmare_b4_xmas.mym",
"freddy.mym",
"nightsintodreams.mym",
"nirvana_stage1.mym",
"nomoreheroes.mym",
"raiders_stage1.mym",
"oasis_stage1.mym",
"okami.mym",
"old_school_nintendo.mym",
"outlawstar.mym",
"outerspace.mym",
"spacev2.mym",
"ozzy.mym",
"pacman.mym",
"pawpatrol.mym",
"pearl_jam.mym",
"penguins_of_madagascar_stage1.mym",
"phoenixwright.mym",
"pikmin.mym",
"pinkfloyd_stage1.mym",
"pinkwii.mym",
"pinkybrain.mym",
"pirateskulls_stage1.mym",
"penguins.mym",
"steelers_stage1.mym",
"pizzatower.mym",
"popeye.mym",
"pokemon.mym",
"predator.mym",
"princess_ariel_v1.mym",
"princess_ariel_v2.mym",
"princess_ariel_v3.mym",
"psychedelic.mym",
"punch_out.mym",
"punisher_stage1.mym",
"randy_orton.mym",
"ratchet_and_clank.mym",
"rc24_blue.mym",
"rc24_red.mym",
"redwiimotion.mym",
"regularshow.mym",
"renstimpy.mym",
"re4.mym",
"rey_mysterio.mym",
"rhythm_heaven.mym",
"ricknmorty.mym",
"ricknmortyv2.mym",
"roblox.mym",
"robot_chicken.mym",
"rockband_2.mym",
"rockosmodernlife.mym",
"rolling_stones.mym",
"rondo_of_blood.mym",
"rugrats.mym",
"saw.mym",
"scarface.mym",
"scoobydoo.mym",
"secretsofmana.mym",
"Seinfeld.mym",
"sendo.mym",
"sesamestreet.mym",
"shadow_the_hedgehog.mym",
"shana_stage1.mym",
"shinedown_stage1.mym",
"silver_the_hedgehog.mym",
"smash_brothers_brawl.mym",
"smokers.mym",
"snoopy.mym",
"sonic3.mym",
"sonicfrontiers.mym",
"sonicriders.mym",
"sonsofanarchy_stage1.mym",
"southpark.mym",
"southparkv2.mym",
"spawn.mym",
"spiceandwolf.mym",
"Spiderman.mym",
"spongebob.mym",
"spongebobv2.mym",
"squid_billies_stage1.mym",
"star_craft.mym",
"starfoxzero.mym",
"star_gate.mym",
"startrek.mym",
"star_wars.mym",
"star_wars_unleashed.mym",
"steel_wii.mym",
"storms",
"street_fighter.mym",
"super_hero_squad.mym",
"supermariobros3.mym",
"super_mario_RPG.mym",
"supermariosunshine.mym",
"superpapermario.mym",
"super_sonic.mym",
"the_simpsons_v1.mym",
"the_simpsons_v2.mym",
"the_simpsons_v3.mym",
"tails_stage1.mym",
"tamagotchi.mym",
"tamagotchiv2.mym",
"terminator.mym",
"terranigma.mym",
"thunder_cats.mym",
"tmnt.mym",
"tenaciousD.mym",
"tomandjerry.mym",
"tomandjerryv2.mym",
"tomb_raider.mym",
"leafs.mym",
"totaldrama_stage1.mym",
"toxic_toons.mym",
"toystory.mym",
"toystoryv2.mym",
"transformers.mym",
"trialsofmana.mym",
"tri-gun.mym",
"tropicalteal.mym",
"true_blood.mym",
"ultimate_dark_wii_stage1.mym",
"usbanimals.mym",
"canucks.mym",
"vegeta.mym",
"vista.mym",
"wackyraces.mym",
"wallacegromit.mym",
"walleye_stage1.mym",
"wario_ware.mym",
"capitals.mym",
"weaponx.mym",
"whereswally.mym",
"white_stripes_stage1.mym",
"white_wii.mym",
"wiid.mym",
"wiiadict.mym",
"wii_fit.mym",
"wiiparty.mym",
"wiipartyv2.mym",
"wii_sports.mym",
"wiistartfires.mym",
"wii_u.mym",
"windows7.mym",
"win_xp_os.mym",
"woodwii.mym",
"woody.mym",
"wolverine.mym",
"wolverinev2.mym",
"wwe_raw.mym",
"xbox360.mym",
"xmen.mym",
"yoshi.mym",
"yugioh.mym",
"zelda.mym",
"zelda2.mym",
"minishcap.mym",
"zelda_v4.mym",
"zombwii.mym"
};
char *Theme_ID[MAXTHEMES] = {
"ADVTIM",
"RLMSTR",
"AMDAD1",
"AMDAD2",
"AMONG1",
"AMONG2",
"ANGBVR",
"ANML01",
"ANML02",
"APPLE1",
"ATHF01",
"AODRK1",
"ARSNFC",
"FALCON",
"AVENG1",
"BACFUT",
"BKGN01",
"BRCLNA",
"BATDRI",
"BTMN01",
"BTMN02",
"BIGG01",
"BILLY1",
"BLKGD1",
"BLMG01",
"BLPR01",
"BLPR02",
"BLKSAB",
"BLCH01",
"BLUCLU",
"BWBETA",
"BOBO01",
"BDSTS1",
"BSTRD1",
"BWSR01",
"BRATZ1",
"BRLY01",
"BILLS1",
"BUFFY1",
"BUSYTN",
"CODTY1",
"CPTCMN",
"CAR001",
"PNTHR1",
"CARS01",
"CSTLV1",
"CATDOG",
"CELTIC",
"CHNSAW",
"CKMO01",
"BEARS1",
"HAWKS1",
"BULLS1",
"CHOWDR",
"XMASSE",
"CRTRG1",
"CLKWK1",
"CLBPN1",
"CD:KND",
"GEASS1",
"CONDT1",
"CONDT2",
"CONST1",
"CURAGE",
"CRETUR",
"DAISYB",
"CWBYS1",
"DANDAN",
"DKUB01",
"DKUB02",
"DWEXT1",
"DKWI+1",
"DWORI1",
"DWBL",
"DWGR",
"DWOR",
"DWPK",
"DWPR",
"DWRD",
"DWWH",
"DWYL",
"DKWSCB",
"DNOTE1",
"DMNSLR",
"DKLOK1",
"LIONS1",
"DEXLAB",
"DIABL1",
"DSCRD1",
"DGMN01",
"DOLPH1",
"DBLZ01",
"DBLZ02",
"DRWTGR",
"DRWHO1",
"DUKES1",
"DGENX1",
"EGLES1",
"ETHBD1",
"ETHBD2",
"ETHBD3",
"EDEDDY",
"EMOBL1",
"EMOGR1",
"EMOPK1",
"EMOPR1",
"EMORD1",
"EVDED1",
"EXBOT1",
"EYES01",
"FODDP1",
"FMGUY1",
"FAN4V1",
"FANTA1",
"FATALB",
"FELIX1",
"FCLUB1",
"FFVII1",
"FIRE01",
"FLINTS",
"FLOPO1",
"FOSTER",
"FNFNK1",
"F13TH1",
"FMTL",
"FUTUR1",
"GAARA1",
"GAMBIT",
"GRFLD1",
"GOWAR1",
"GBUST1",
"GIJOE1",
"GSUN01",
"GORILA",
"GOTH01",
"GRTFL1",
"PCKRS1",
"GABLMD",
"GUMBLL",
"GUNDAM",
"HDRAW1",
"HAPYTF",
"HKITY1",
"HELLK1",
"HEMAN1",
"HEROS1",
"ARMOLD",
"HMESTR",
"WHEEL1",
"HNDRD1",
"ICARLY",
"ILLOG1",
"IMPOR1",
"INBET1",
"INDYJO",
"COLTS1",
"ICP001",
"IMMAR1",
"JNSBOB",
"JETSON",
"JSRAD1",
"JNUTR1",
"JNUTR2",
"JOKER1",
"JRPRK1",
"JURWLD",
"KDICR1",
"KHRT01",
"KOTHV1",
"KIRBY1",
"KIRBY2",
"KISS01",
"KORN01",
"LEGO01",
"LGOBTM",
"LEOPA1",
"LIME01",
"LMPBIZ",
"LTOON1",
"LARAMS",
"LOST01",
"LUIGI1",
"LUIGI2",
"LACPIE",
"LUPIN3",
"MNMS01",
"MWRLD1",
"MWRLD2",
"MAMSK1",
"UNITED",
"MNHNT1",
"MARIA1",
"MARIO2",
"MKART1",
"PARTY8",
"MABEL1",
"MATRX1",
"MATRX2",
"MEGMN1",
"MOHAR1",
"MGSOL1",
"MTLCA1",
"MTROD1",
"METPR1",
"MTDSV1",
"METS01",
"MINECR",
"MINION",
"MNION2",
"MISTF1",
"MODMII",
"MONKEY",
"MONOW1",
"MONSTR",
"CANAD1",
"MKOMB1",
"MRDRIL",
"MUSE01",
"MYHERO",
"MYPONY",
"NARTO1",
"SAINT1",
"NEPAT1",
"RANGR1",
"YANKE1",
"NMB4X1",
"FREDDy",
"NIDRM1",
"NRVNA1",
"NOMRH1",
"RAIDR1",
"OASIS1",
"OKAMI1",
"OSNIN1",
"OTLWS1",
"SPACE1",
"SPACE2",
"OZZY01",
"PACMAN",
"PWPTRL",
"PLJAM1",
"POMAD1",
"PHWRT1",
"PIKMN1",
"PKFLD1",
"PNKWI1",
"PNKBRN",
"PRSKL1",
"PENGUN",
"STELR1",
"PIZTR1",
"POPEYE",
"POKEMN",
"PREDR1",
"PARIE1",
"PARIE2",
"PARIE3",
"PSYCO1",
"PNOUT1",
"PUNSH1",
"ORTON1",
"RCLNK1",
"RC2402",
"RC2401",
"REDMO1",
"REGSHW",
"RENSTM",
"RESEVE",
"RMYST1",
"RHYTH1",
"RMORT1",
"RMORT2",
"ROBLOX",
"RCHCK1",
"RBAND1",
"ROCKOS",
"STONES",
"RBLOD1",
"RUGRAT",
"SAW001",
"SCRFC1",
"SCOOBY",
"SECOM1",
"SEINF1",
"SENDO1",
"SESAME",
"SHADH1",
"SHANA1",
"SHNDWN",
"SILVH1",
"SMASH1",
"SMOKE1",
"SNOOP1",
"SONIC3",
"SNCFT1",
"SNCRD1",
"SONOA1",
"STHPK1",
"STHPK2",
"SPAWN1",
"SPICE1",
"SPDMN1",
"SPONG1",
"SPONG2",
"SQUBL1",
"STCFT1",
"STARFX",
"STGTE1",
"STRTRK",
"STWRS1",
"STWRS2",
"STWII1",
"STRM",
"STRFT1",
"SHSQU1",
"SMARB3",
"SMRPG1",
"SMSUN1",
"SPAPM1",
"SSONI1",
"SIMPS1",
"SIMPS2",
"SIMPS3",
"TAILS1",
"TAMAGO",
"TAMAG2",
"TERMR1",
"TERNG1",
"TCATS1",
"TMNT01",
"TENACD",
"TOMJER",
"TMJER2",
"TRAID1",
"LEAFS1",
"TOTDR1",
"TTOON1",
"TOYST1",
"TOYST2",
"TRANS1",
"TRLOM1",
"TRGUN1",
"TRPTL1",
"TBLOD1",
"UDWII1",
"USBANI",
"CANUCK",
"VEGET1",
"VISTA1",
"WACKY1",
"WALACE",
"WALEY1",
"WARIO1",
"CAPTLS",
"WEAPNX",
"WWALDO",
"WSTRI1",
"WHITE1",
"WIID01",
"WIIADC",
"WIFIT1",
"WIIPT1",
"WIIPT2",
"WSPOR1",
"WIISTR",
"WIIU01",
"WIN701",
"WINXP1",
"WOODWI",
"WOODYP",
"WOLVE1",
"WOLVE2",
"WWERW1",
"XBOX01",
"XMENV1",
"GYOSHI",
"YUGIO1",
"ZELDA1",
"ZELDA2",
"ZELDA3",
"ZELDA4",
"ZOMB01"
};
char *Theme_Download_Txt[MAXTHEMES] = {
"adventuretime.txt",
"realmonsters.txt",
"american_dad.txt",
"american_dadv2.txt",
"amongusv1.txt",
"amongusv2.txt",
"angrybeavers.txt",
"animal_crossing.txt",
"animal_crossing_v2.txt",
"apple.txt",
"aqua_teen_hunger_force.txt",
"army_of_darkness.txt",
"arsenal.txt",
"falcons.txt",
"avengers.txt",
"backtothefuture.txt",
"bakugan.txt",
"barcelona.txt",
"battlefordreamisland.txt",
"batman_v1.txt",
"batman_v2.txt",
"biggie.txt",
"billymays.txt",
"blackgold.txt",
"black_mage.txt",
"black_pirate.txt",
"black_piratev2.txt",
"blacksabbath.txt",
"bleach.txt",
"bluesclues.txt",
"bluewii_beta.txt",
"bobobo.txt",
"boondock_saints.txt",
"boston_redsocks.txt",
"bowser.txt",
"bratz.txt",
"broly.txt",
"buffalo_bills.txt",
"buffy.txt",
"busytown.txt",
"call_of_duty.txt",
"caveman.txt",
"car.txt",
"panthers.txt",
"cars.txt",
"castlevania.txt",
"catdog.txt",
"celtic.txt",
"chainsaw_man.txt",
"check_mii_out.txt",
"bears.txt",
"blackhawks.txt",
"bulls.txt",
"chowder.txt",
"xmas.txt",
"chronotrigger.txt",
"clockworkorange.txt",
"clubpenguin.txt",
"knd.txt",
"code_geass.txt",
"conduit.txt",
"conduitv2.txt",
"constantine.txt",
"courage.txt",
"creature_cases.txt",
"daisy.txt",
"cowboys.txt",
"dandadan.txt",
"dark_umbra_v1.txt",
"dark_umbra_v2.txt",
"darkwii_extended.txt",
"darkwii_plus.txt",
"dark_wii_original.txt",
"dark_wii_blue.txt",
"dark_wii_green.txt",
"dark_wii_orange.txt",
"dark_wii_pink.txt",
"dark_wii_purple.txt",
"dark_wii_red.txt",
"dark_wii_white.txt",
"dark_wii_yellow.txt",
"dark_scooby.txt",
"deathnote.txt",
"demonslayer.txt",
"deth_klok.txt",
"lions.txt",
"dexterslab.txt",
"diablo_3.txt",
"discord.txt",
"dogman.txt",
"dolphins.txt",
"dragon_ball_z_v1.txt",
"dragon_ball_z_v2.txt",
"drawntogether.txt",
"dr_who.txt",
"dukes.txt",
"dx.txt",
"eagles.txt",
"earth_bound.txt",
"earth_boundv2.txt",
"earth_boundv3.txt",
"ededdeddy.txt",
"emoblue.txt",
"emogreen.txt",
"emopink.txt",
"emopurple.txt",
"emored.txt",
"evil_dead.txt",
"excite_bots.txt",
"eyes.txt",
"fairlyoddparents.txt",
"family_guy.txt",
"fantasticfour.txt",
"fantasy.txt",
"fatalbert.txt",
"felix.txt",
"fight_club.txt",
"final_fantasy_7.txt",
"fire_wii.txt",
"flintstones.txt",
"flowerpower.txt",
"fosters_home.txt",
"fridaynightfunkin.txt",
"fridaythe13th.txt",
"full_metal_alchemist.txt",
"futurama.txt",
"gaara.txt",
"gambit.txt",
"garfield.txt",
"gears_of_war.txt",
"ghost_busters.txt",
"gijoe.txt",
"golden_sun.txt",
"gorillaz.txt",
"gothic.txt",
"gratefuldead.txt",
"packers.txt",
"grim.txt",
"gumball.txt",
"gundam.txt",
"hand_drawn.txt",
"treefriends.txt",
"hello_kitty.txt",
"hellskitchen.txt",
"heman.txt",
"heros.txt",
"arnold.txt",
"homestar.txt",
"hot_wheels.txt",
"hundreds.txt",
"icarly.txt",
"illusionsofgaia.txt",
"imports.txt",
"in_betweeners.txt",
"indianajones.txt",
"colts.txt",
"insane_clown_posse.txt",
"itsamemario.txt",
"jaybob.txt",
"jetsons.txt",
"jetsetradio.txt",
"jimmyneutron.txt",
"jimmyneutronv2.txt",
"joker.txt",
"jurassic_park_3.txt",
"jurassicworld.txt",
"kidicarus.txt",
"kingdom_hearts.txt",
"kingofthehill.txt",
"kirby.txt",
"kirbyadventures.txt",
"kiss.txt",
"korn.txt",
"lego.txt",
"legobatman.txt",
"leopard_os.txt",
"lime_wii.txt",
"limpbizkit.txt",
"looney_toons.txt",
"larams.txt",
"lost.txt",
"luigi.txt",
"luigiv2.txt",
"luna_chip_inkie.txt",
"lupin.txt",
"mms.txt",
"mad_world.txt",
"mad_world_v2.txt",
"majoras_mask.txt",
"united.txt",
"manhunt.txt",
"maria.txt",
"mario.txt",
"mario_kart.txt",
"marioparty8.txt",
"martin_abel.txt",
"matrix.txt",
"matrix_reloaded.txt",
"megaman.txt",
"melonofharuhi.txt",
"metal_gear_solid.txt",
"metallica.txt",
"metroid.txt",
"metroid_prime.txt",
"metroid_samusvisor.txt",
"mets.txt",
"minecraft.txt",
"minions.txt",
"minionsv2.txt",
"mistforest.txt",
"modmii.txt",
"monkeys.txt",
"monopoly.txt",
"monsters_inc.txt",
"canadians.txt",
"mortal_kombat.txt",
"mrdriller.txt",
"muse.txt",
"myhero.txt",
"poni.txt",
"naruto.txt",
"saints.txt",
"patriots.txt",
"rangers.txt",
"yankees.txt",
"nightmare_b4_xmas.txt",
"freddy.txt",
"nightsintodreams.txt",
"nirvana.txt",
"nomoreheros.txt",
"raiders.txt",
"oasis.txt",
"okami.txt",
"old_school_nintendo.txt",
"outlawstar.txt",
"outerspace.txt",
"spacev2.txt",
"ozzy.txt",
"pacman.txt",
"pawpatrol.txt",
"pearl_jam.txt",
"penguinsofmad.txt",
"phoenixwright.txt",
"pikmin.txt",
"pinkfloyd.txt",
"pinkwii.txt",
"pinkybrain.txt",
"pirateskulls.txt",
"penguins.txt",
"steelers.txt",
"pizzatower.txt",
"popeye.txt",
"pokemon.txt",
"predator.txt",
"princess_ariel_v1.txt",
"princess_ariel_v2.txt",
"princess_ariel_v3.txt",
"psychedelic.txt",
"punch_out.txt",
"punisher.txt",
"randyorton.txt",
"ratchet_and_clank.txt",
"rc24_blue.txt",
"rc24_red.txt",
"redwiimotion.txt",
"renstimpy.txt",
"re4.txt",
"rey_mysterio.txt",
"rhythmheaven.txt",
"ricknmorty.txt",
"ricknmortyv2.txt",
"roblox.txt",
"robot_chicken.txt",
"rockband_2.txt",
"rockosmodernlife.txt",
"rollingstones.txt",
"rondo_of_blood.txt",
"rugrats.txt",
"saw.txt",
"scarface.txt",
"scoobydoo.txt",
"secretsofmana.txt",
"Seinfeld.txt",
"sendo.txt",
"sesamestreet.txt",
"shadow_the_hedgehog.txt",
"shana.txt",
"shinedown.txt",
"silver_the_hedgehog.txt",
"smashbros.txt",
"smokers.txt",
"snoopy.txt",
"sonic3.txt",
"sonicfrontiers.txt",
"sonicriders.txt",
"sonsofanarchy.txt",
"southpark.txt",
"southparkv2.txt",
"spawn.txt",
"spiceandwolf.txt",
"Spiderman.txt",
"spongebob.txt",
"spongebobv2.txt",
"squidbillies.txt",
"starcraft.txt",
"starfoxzero.txt",
"stargate.txt",
"startrek.txt",
"starwars.txt",
"starwarsunleashed.txt",
"steelwii.txt",
"storms.txt",
"streetfighter.txt",
"super_hero_squad.txt",
"supermariobros3.txt",
"super_mario_RPG.txt",
"supermariosunshine.txt",
"superpapermario.txt",
"super_sonic.txt",
"the_simpsons_v1.txt",
"the_simpsons_v2.txt",
"the_simpsons_v3.txt",
"tails.txt",
"tamagotchi.txt",
"tamagotchiv2.txt",
"terminator.txt",
"terranigma.txt",
"thunder_cats.txt",
"tmnt.txt",
"tenaciousD.txt",
"tomandjerry.txt",
"tomandjerryv2.txt",
"tomb_raider.txt",
"leafs.txt",
"totaldrama.txt",
"toxictoons.txt",
"toystory.txt",
"toystoryv2.txt",
"transformers.txt",
"trialsofmana.txt",
"trigun.txt",
"tropicalteal.txt",
"true_blood.txt",
"ultimatedarkwii.txt",
"usbanimals.txt",
"canucks.txt",
"vegeta.txt",
"vista.txt",
"wackyraces.txt",
"wallacegromit.txt",
"walleye.txt",
"warioware.txt",
"capitals.txt",
"weaponx.txt",
"whereswally.txt",
"whitestripes.txt",
"whitewii.txt",
"wiid.txt",
"wiiadict.txt",
"wiifit.txt",
"wiiparty.txt",
"wiipartyv2.txt",
"wiisports.txt",
"wiistartfires.txt",
"wiiu.txt",
"windows7.txt",
"win_xp_os.txt",
"woodwii.txt",
"woodywoodpecker.txt",
"wolverine.txt",
"wolverinev2.txt",
"wweraw.txt",
"xbox360.txt",
"xmen.txt",
"yoshi.txt",
"yugioh.txt",
"zelda.txt",
"zelda2.txt",
"minishcap.txt",
"zelda_v4.txt",
"zombwii.txt"
};
#endif // THEMEDATABASE_H