#ifndef THEMEDATABASE_H
#define THEMEDATABASE_H

const char *Theme_Png[MAXTHEMES] = {
	"animalcrossing.png",
	"aquateenhungerforce.png",
	"bakugan.png",
	"batmanv1.png",
	"batmanv2.png",
	"blackmage.png",
	"blackpirate.png",
	"bleach.png",
	"boondocksaints.png",
	"bowser.png",
	"broly.png",
	"call_of_duty.png",
	"car.png",
	"cars.png",
	"check_mii_out.png",
	"codegeass.png",
	"constantine.png",
	"dark_umbra_v1.png",
	"dark_umbra_v2.png",
	"darkwiioriginal.png",
	"darkwiiblue.png",
	"darkwiigreen.png",
	"darkwiiorange.png",
	"darkwiipink.png",
	"darkwiipurple.png",
	"darkwiired.png",
	"darkwiiwhite.png",
	"darkwiiyellow.png",
	"dethklok.png",
	"diablo_3.png",
	"discord.png",
	"dragonballzv1.png",
	"dragonballzv2.png",
	"drwho.png",
	"earthbound.png",
	"evildead.png",
	"excitebots.png",
	"eyes.png",
	"fairlyoddparents.png",
	"familyguy.png",
	"fantasy.png",
	"fightclub.png",
	"finalfantasy7.png",
	"firewii.png",
	"flowerpower.png",
	"fridaynightfunkin.png",
	"fridaythe13th.png",
	"fullmetalalchemist.png",
	"futurama.png",
	"gaara.png",
	"gearsofwar.png",
	"ghostbusters.png",
	"goldensun.png",
	"gothic.png",
	"handdrawn.png",
	"hellokitty.png",
	"heman.png",
	"heros.png",
	"inbetweeners.png",
	"icp.png",
	"itsamemario.png",
	"joker.png",
	"jurassicpark3.png",
	"kingdomhearts.png",
	"kirby.png",
	"korn.png",
	"leopardOS.png",
	"limewii.png",
	"looneytoons.png",
	"lost.png",
	"luigiv1.png",
	"luigiv2.png",
	"madworld.png",
	"mad_world_v2.png",
	"majorasmask.png",
	"mario.png",
	"mariokart.png",
	"martin_abel.png",
	"matrix.png",
	"matrixreloaded.png",
	"megaman.png",
	"metalgearsolid.png",
	"metallica.png",
	"metroid.png",
	"mortalkombat.png",
	"muse.png",
	"naruto.png",
	"nightmareb4xmas.png",
	"okami.png",
	"oldschoolnintendo.png",
	"pearl_jam.png",
	"pikmin.png",
	"pinkwii.png",
	"predator.png",
	"princess_ariel_v1.png",
	"princess_ariel_v2.png",
	"princess_ariel_v3.png",
	"psychedelic.png",
	"punchout.png",
	"punisher.png",
	"ratchetandclank.png",
	"robotchicken.png",
	"rockband2.png",
	"saw.png",
	"shadowthehedgehog.png",
	"silverthehedgehog.png",
	"smashbros.png",
	"snoopy.png",
	"spawn.png",
	"Spiderman.png",
	"spongebob.png",
	"squidbillies.png",
	"starcraft.png",
	"stargate.png",
	"starwars.png",
	"starwarsunleashed.png",
	"steelwii.png",
	"storms.png",
	"streetfighter.png",
	"superherosquad.png",
	"supermarioRPG.png",
	"supersonic.png",
	"tails.png",
	"thesimpsons_v1.png",
	"thesimpsons_v2.png",
	"thesimpsons_v3.png",
	"terminator.png",
	"thundercats.png",
	"tmnt.png",
	"tombraider.png",
	"toxictoons.png",
	"transformers.png",
	"trigun.png",
	"trueblood.png",
	"ultimatedarkwii.png",
	"vegeta.png",
	"vista.png",
	"walleye.png",
	"warioware.png",
	"whitestripes.png",
	"whitewii.png",
	"wiid.png",
	"wiifit.png",
	"wiisports.png",
	"wiiu.png",
	"winxpos.png",
	"wolverine.png",
	"wweraw.png",
	"xbox360.png",
	"yugioh.png",
	"zelda.png",
	"zombwii.png"
};


const char *DBThemelist[MAXTHEMES] = {
	"Animal Crossing",
	"Aqua Teen Hunger Force",
	"Bakugan",
	"Batman v1",
	"Batman v2",
	"Black Mage",
	"Black Pirate",
	"Bleach",
	"Boondock Saints",
	"Bowser",
	"Broly",
	"Call of Duty",
	"Car",
	"Cars",
	"Check Me Out",
	"Code Geass",
	"Constantine",
	"Dark Umbra v1",
	"Dark Umbra v2",
	"Dark Wii Original",
	"Dark Wii Blue",
	"Dark Wii Green",
	"Dark Wii Orange",
	"Dark Wii Pink",
	"Dark Wii Purple",
	"Dark Wii Red",
	"Dark Wii White",
	"Dark Wii Yellow",
	"Deth Klok",
	"Diablo 3",
	"Discord",
	"Dragon Ball Z v1",
	"Dragon Ball Z v2",
	"Dr Who",
	"Earth Bound",
	"Evil Dead",
	"Excite Bots",
	"Eyes",
	"Fairly Odd Parents",
	"Family Guy",
	"Fantasy",
	"Fight Club",
	"Final Fantasy 7",
	"Fire Wii",
	"Flower Power",
	"Friday Night Funkin",
	"Friday the 13th",
	"Full Metal Alchemist",
	"Futurama",
	"Gaara",
	"Gears of War",
	"Ghost Busters",
	"Golden Sun",
	"Gothic",
	"Hand Drawn",
	"Hello Kitty",
	"He-Man",
	"Heros",
	"In Betweeners",
	"Insane Clown Posse",
	"Its A Me Mario",
	"Joker",
	"Jurassic Park 3",
	"Kingdom Hearts",
	"Kirby",
	"Korn",
	"Leopard OS",
	"Lime Wii",
	"Looney Toons",
	"Lost",
	"Luigi v1",
	"Luigi v2",
	"Mad World",
	"Mad World v2",
	"Majoras Mask",
	"Mario",
	"Mario Kart",
	"Martin Abel Art",
	"Matrix",
	"Matrix Reloaded",
	"Mega-Man",
	"Metal Gear Solid",
	"Metallica",
	"Metroid",
	"Mortal Kombat",
	"Muse",
	"Naruto",
	"Nightmare B4 Xmas",
	"Okami",
	"Old School Nintendo",
	"Pearl Jam",
	"Pikmin",
	"Pink Wii",
	"Predator",
	"Princess Ariel v1",
	"Princess Ariel v2",
	"Princess Ariel v3",
	"Psychedelic",
	"Punch Out",
	"Punisher",
	"Ratchet and Clank",
	"Robot Chicken",
	"Rockband 2",
	"Saw",
	"Shadow The HedgeHog",
	"Silver The HedgeHog",
	"Smash Brothers Brawl",
	"Snoopy",
	"Spawn",
	"Spiderman",
	"Sponge Bob",
	"Squid Billies",
	"Star Craft",
	"Star Gate",
	"Star Wars",
	"Star Wars: Unleashed",
	"Steel Wii",
	"Storms",
	"Street Fighter",
	"Super Hero Squad",
	"Super Mario RPG",
	"Super Sonic",
	"Tails",
	"The Simpsons v1",
	"The Simpsons v2",
	"The Simpsons v3",
	"The Terminator",
	"Thunder Cats",
	"TMNT",
	"Tomb Raider",
	"Toxic Toons",
	"Transformers",
	"Tri Gun",
	"True Blood",
	"Ultimate Dark Wii",
	"Vegeta",
	"Vista",
	"Walleye",
	"Wario Ware",
	"White Stripes",
	"White Wii",
	"Wiid",
	"Wii Fit",
	"Wii Sports",
	"Wii U",
	"Win XP OS",
	"Wolverine",
	"WWE Raw",
	"Xbox 360",
	"Yugi oh",
	"Zelda",
	"Zombwii"
};
const char *DBThemelist_nospaces[MAXTHEMES] = {
	"AnimalCrossing",
	"AquaTeenHungerForce",
	"Bakugan",
	"Batmanv1",
	"Batmanv2",
	"BlackMage",
	"BlackPirate",
	"Bleach",
	"BoondockSaints",
	"Bowser",
	"Broly",
	"CallofDuty",
	"Car",
	"Cars",
	"CheckMeOut",
	"CodeGeass",
	"Constantine",
	"DarkUmbrav1",
	"DarkUmbrav2",
	"DarkWiiOriginal",
	"DarkWiiBlue",
	"DarkWiiGreen",
	"DarkWiiOrange",
	"DarkWiiPink",
	"DarkWiiPurple",
	"DarkWiiRed",
	"DarkWiiWhite",
	"DarkWiiYellow",
	"DethKlok",
	"Diablo3",
	"Discord",
	"DragonBallZv1",
	"DragonBallZv2",
	"DrWho",
	"EarthBound",
	"EvilDead",
	"ExciteBots",
	"Eyes",
	"FairlyOddParents",
	"FamilyGuy",
	"Fantasy",
	"FightClub",
	"FinalFantasy7",
	"FireWii",
	"FlowerPower",
	"FridayNightFunkin",
	"Fridaythe13th",
	"FullMetalAlchemist",
	"Futurama",
	"Gaara",
	"GearsofWar",
	"GhostBusters",
	"GoldenSun",
	"Gothic",
	"HandDrawn",
	"HelloKitty",
	"He-Man",
	"Heros",
	"InBetweeners",
	"InsaneClownPosse",
	"ItsAMeMario",
	"Joker",
	"JurassicPark3",
	"KingdomHearts",
	"Kirby",
	"Korn",
	"LeopardOS",
	"LimeWii",
	"LooneyToons",
	"Lost",
	"Luigiv1",
	"Luigiv2",
	"MadWorld",
	"MadWorldv2",
	"MajorasMask",
	"Mario",
	"MarioKart",
	"MartinAbelArt",
	"Matrix",
	"MatrixReloaded",
	"Mega-Man",
	"MetalGearSolid",
	"Metallica",
	"Metroid",
	"Metroid",
	"MortalKombat",
	"Muse",
	"Naruto",
	"Okami",
	"NightmareB4Xmas",
	"OldSchoolNintendo",
	"PearlJam",
	"Pikmin",
	"PinkWii",
	"Predator",
	"PrincessArielv1",
	"PrincessArielv2",
	"PrincessArielv3",
	"Psychedelic",
	"PunchOut",
	"Punisher",
	"RatchetandClank",
	"RobotChicken",
	"Rockband2",
	"Saw",
	"ShadowTheHedgeHog",
	"SilverTheHedgeHog",
	"SmashBrothersBrawl",
	"Snoopy",
	"Spawn",
	"Spiderman",
	"SpongeBob",
	"SquidBillies",
	"StarCraft",
	"StarGate",
	"StarWars",
	"StarWars:Unleashed",
	"SteelWii",
	"Storms",
	"StreetFighter",
	"SuperHeroSquad",
	"SuperMarioRPG",
	"SuperSonic",
	"Tails",
	"TheSimpsonsv1",
	"TheSimpsonsv2",
	"TheSimpsonsv3",
	"TheTerminator",
	"ThunderCats",
	"TMNT",
	"TombRaider",
	"ToxicToons",
	"Transformers",
	"TriGun",
	"TrueBlood",
	"UltimateDarkWii",
	"Vegeta",
	"Vista",
	"Walleye",
	"WarioWare",
	"WhiteStripes",
	"WhiteWii",
	"Wiid",
	"WiiFit",
	"WiiSports",
	"WiiU",
	"WinXPOS",
	"Wolverine",
	"WWERaw",
	"Xbox360",
	"Yugioh",
	"Zelda",
	"Zombwii"
};

const char *Theme_Mym_File[MAXTHEMES] = {
	"animal_crossing.mym",
	"aqua_teen_hunger_forcestage1.mym",
	"bakugan.mym",
	"batman_v1.mym",
	"batman_v2.mym",
	"black_mage.mym",
	"black_pirate.mym",
	"bleach.mym",
	"boondock_saints.mym",
	"bowser.mym",
	"broly.mym",
	"call_of_duty.mym",
	"car.mym",
	"carsstage1.mym",
	"check_mii_out.mym",
	"code_geass.mym", 
	"constantine.mym", // 10
	"dark_umbra_v1.mym",
	"dark_umbra_v2.mym",
	"dark_wii_original.mym",
	"dark_wii_blue",
	"dark_wii_green",
	"dark_wii_orange",
	"dark_wii_pink",
	"dark_wii_purple",
	"dark_wii_red",
	"dark_wii_white",
	"dark_wii_yellow",
	"deth_klok.mym",
	"diablo_3.mym",
	"discord.mym",
	"dragon_ball_z_v1.mym",
	"dragon_ball_z_v2.mym",
	"dr_who.mym",
	"earth_bound.mym",
	"evil_dead.mym",
	"excite_bots.mym",
	"eyes.mym",
	"fairly_odd_parentsstage1.mym",
	"family_guy.mym",
	"fantasy.mym",
	"fight_club.mym",
	"final_fantasy_7.mym",
	"fire_wii.mym",
	"flower_powerstage1.mym",
	"friday_night_funkin.mym",
	"friday_the_13thstage1.mym",
	"full_metal_alchemist",
	"futurama.mym",
	"gaara.mym",
	"gears_of_war.mym",
	"ghost_busters.mym",
	"golden_sun.mym",
	"gothic.mym",
	"hand_drawn.mym",
	"hello_kitty.mym",
	"he-manstage1.mym",
	"heros.mym",
	"In_betweeners.mym",
	"Insane_clown_posse.mym",
	"itsamemario.mym",
	"jokerstage1.mym",
	"jurassic_park_3.mym",
	"kingdom_hearts.mym",
	"kirby.mym",
	"korn.mym",
	"leopard_os.mym",
	"lime_wii.mym",
	"looney_toons.mym",
	"Lost.mym",
	"luigi_v1.mym.mym",
	"luigi_v2stage1.mym",
	"mad_world.mym",
	"mad_world2.mym",
	"majoras_mask.mym",
	"mario.mym",
	"mario_kart.mym",
	"martin_abel.mym",
	"matrix.mym",
	"matrix_reloaded.mym",
	"megaman.mym",
	"metal_gear_solid.mym",
	"metallica.mym",
	"metroid.mym",
	"mortal_kombat.mym",
	"muse.mym",
	"naruto.mym",
	"nightmare_b4_xmas.mym",
	"okami.mym",
	"old_school_nintendo.mym",
	"pearl_jam.mym",
	"Pikmin.mym",
	"pinkwii.mym",
	"predator.mym",
	"princess_ariel_v1.mym",
	"princess_ariel_v2.mym",
	"princess_ariel_v3.mym",
	"psychedelic.mym",
	"punch_out.mym",
	"punisherstage1.mym",
	"ratchet_and_clank.mym",
	"robot_chicken.mym",
	"rockband_2.mym",
	"saw.mym",
	"shadow_the_hedgehog.mym",
	"silver_the_hedgehog.mym",
	"smash_brothers_brawl.mym",
	"snoopy.mym",
	"Spawn.mym",
	"Spiderman.mym",
	"spongebob.mym",
	"squid_billiesstage1.mym",
	"star_craft.mym",
	"star_gate.mym",
	"star_wars.mym",
	"star_wars_unleashed.mym",
	"steel_wii.mym",
	"storms",
	"street_fighter.mym",
	"super_hero_squad.mym",
	"super_mario_RPG.mym",
	"super_sonic.mym",
	"tailsstage1.mym",
	"the_simpsons_v1.mym",
	"the_simpsons_v2.mym",
	"the_simpsons_v3.mym",
	"terminator.mym",
	"thunder_cats.mym",
	"tmnt.mym",
	"tomb_raider.mym",
	"toxic_toons.mym",
	"transformers.mym",
	"tri-gun.mym",
	"true_blood.mym",
	"ultimate_dark_wiistage1.mym",
	"Vegeta.mym",
	"vista.mym",
	"walleye_stage1.mym",
	"wario_ware.mym",
	"white_stripesstage1.mym",
	"white_wii.mym",
	"wiid.mym",
	"wii_fit.mym",
	"wii_sports.mym",
	"wii_u.mym",
	"win_xp_os.mym",
	"wolverine.mym",
	"wwe_raw.mym",
	"xbox360.mym",
	"yugioh.mym",
	"zelda.mym",
	"zombwii.mym"
};
#endif // THEMEDATABASE_H